---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actions

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./arc-controller/ks.yaml
  - ./forgejo-runner/ks.yaml
  - ./arc-runner-set-rxr-cluster/ks.yaml
