apiVersion: v1
kind: Secret
metadata:
  name: copilot-peer
  namespace: copilot-peer
type: Opaque
stringData:
  COPILOT_GITHUB_TOKEN: ENC[AES256_GCM,data:1I07yac2ER0WKgBiyTqT0geN0rPYAYOe6kLoRcADmFqPIZJLMyl7HH9ZpYNKtdE7XXXj0/xtL3E/lGZVLY437EopMXblBxbS2as/wXh+502RydCFTiDdr35EvSex,iv:SWVJC+cFoxz9UhkWK5rIa5xvnyqD44ovOeVx6OPvUJA=,tag:+dpEfeHSN4KPGCndNHrzww==,type:str]
  #ENC[AES256_GCM,data:WEbQaA3e4+eQCvE0SHjkjPyZ04mhQMwiQl8rxItACrHkrwfRErRfq9EE+GfdSWdglCB1tc0t1pA9qv4FwNT2Esv4MqH+ifX22Lpy,iv:sKmSvC4kSqCtaB6/os38zDvNkgPccciwzaZ0e8jUjFY=,tag:v7CZbx0rNeJJt16novXEzA==,type:comment]
  A2A_SHIM_AUTH_TOKEN: ENC[AES256_GCM,data:nZ2XLoHnZJHG6SnktunwPrd0iv1RnB8BJ2vTKi8IIt2ebB6K9YwiVcyLq5lhXwD8dlr9HjGpmYfzcnWhTAI0ig==,iv:ETZrvWZqTaD65aro27m23dOUC5LaCMAqBptwISXC52E=,tag:satHvM2mDBuHJRde7CcouA==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaTF3WThDaWpHSTlra0E2
        cUR0cFBxeTBqYmNCRmRXOFZkTFFOakpHZEJZCkN6aXk2QlBCcFMrdlhySUIwVTdw
        MkhrNjFvaEJ0WGkwQS82RzlkWDVPYk0KLS0tIHhBYzhtaUhHNTNQSkV5MHY5aURS
        cDB1SGlqOVhKaUp5dTRya096dHZsWDQKCblIEydnOjRUK8BnWbSJjkviQ45RjYKn
        wRJy5PWpN88yn5tcT5WFpWB6eG1xQfL8VT1gQxoKVT5gH4Id9erTvg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-10T21:24:54Z"
  mac: ENC[AES256_GCM,data:WiF2U0Nsbdwc9h2Wg32Oxx+whLfBtsPahU4gbsBgXw98OlHmsSWStu+D82l/stgaWwikn38V907E29zwMKgM5pO4/QJcoaiP0YscJXLeN27JDwEHNDU4IiXtGGTh7z8XFjmRVpyKb6Qc0pCQ/A2I0h8F0M2ZyrstngrtrfaSnV0=,iv:atEGAa77GdYUgXUMbeKJ5bPEa9vkPCMDoqmVnt7hPKE=,tag:BIhS2lBspETljaPa+IK2Wg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
