apiVersion: v1
kind: Secret
metadata:
  name: internal-registry-auth
  namespace: copilot-peer
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:FcrGlK66uX2fWm8RsvoRUAf9waxD28Go+M1vpb3w/Gbz9DtDEJb8KyKODklPlP5Y1uMbUR6GF/1dTLCC3FT3tmjNoeK8MzfiyhGhoB8TtX+Wd5gnnNEUFskKT1chGGcwFTzLR5d9ucMCg4rv9bG4xs0SW4YmzbYRUXhGGUT6SFbjSJFpjPy4fBA+u5SjbzUtA1hZWHCnW9co7i5d1bTMyBIVn59GDcaC3yNG4rIG7pMi3o0+zs2etCRNTu4s+oOICX/4m7QpCKKzcMDs+zCxe9X7Rg8iDKZzk3RiE8KyECZQVm4Z,iv:0NyrgSs8nzENc6hNtly05Cp2qSy7xtYfSD07vgLyh04=,tag:ItmakGZ4aIMcaZL6lOvi+Q==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RFpSUmVIWThSNTdNdVUr
        amRTaVlDMytURXFuWkJYSWhzbW9UaWMvdm1ZCmNTVEsvTnVrR2RmUmYyV0QwZC9o
        aWl3NEhDY1NnODRKcWFGcTA2ZS9kWEEKLS0tIERTczdRR0JwMXE2Vlk5UkFzZmZZ
        SFBvWlBSaGhFVmd0d0hyamlVUzhlTm8KhdODtwVkpLqREKwgbTVPzNdoXLVrDk4M
        hKG4Dqvc/PaSzUnUF6OrxdoAPaDBky55Ii+3T5LH/nuPyd5Kv39NmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-10T21:24:54Z"
  mac: ENC[AES256_GCM,data:KeeeMIu9mVkt68MYWXCtyX1ywNsCtjvYmYJonh2GKY2VXby5mFVG1JSzo1mlMXFSAf/wfsTpqlNt2dAL1xD9o2LxcBtfoYDmCo+BFLW1FxfboXKcp6Z8GMDKMaFnTPSapBxJhhZYY6LiusWgCj/KQJRaSvbUR26azxeD1iSeoFM=,iv:efVkxwSI781EfLEY+yzExj54RX/QtMeDXVhUTj4/ak4=,tag:0AY3smTrwWRec8jqCt7+hw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
