apiVersion: v1
kind: Secret
metadata:
  name: kuma-metrics-key
  namespace: automation
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:8TIFXhdY19u/YGncUhFfd+kW98Re11l6ktJEtbBloX7+cN2ipDXJ9pWO8NE=,iv:/0PRb2U3ufd8tXsnkaNSGVrlnIYGhcsm5sgfQ2U0ecg=,tag:epSVpCk0q6xLO+w+el804Q==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZTBTdWlqeW5GVnAwSWJm
        VGFBY1oybmJoQjhJV1FjTDRvRmVGMkc0NzJBCmJpVXZ0bFlnZWRhUWNPUVdkUGlt
        Ti81YUJTUVdsbllnRmVrWW5EY3krZlkKLS0tIGdqK2p6VkRwUTJmR1kvVE85WjN2
        cWVEMVRIWXl0cEd4dDZCczdMMWFKcFUKV+b9NzSzSOVVUZ1Dun8fHLUsEYChshBs
        6QJ+Xe8G7Z2/Swd/aaLeDRjCykbdAD4s04gZBwhgoJ0hewbTo+hHPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-13T21:35:53Z"
  mac: ENC[AES256_GCM,data:zvd2gG/cbjU1sLUJhiTnqNNYrEzHjGfOgd+KfHVjfIR3UiIlceLRgLkZoizj5lIVjblzrnuQEL/IGA7ojIfNJeAky5r20YEyjggX0MthmxeG8kFpWNxyQgWj9JLSo0y35EXuBuwYriqRQJG7Mm8XVWtjtSrI9GqBvHuDqBxsJ2w=,iv:J6eY281ZMUhoGG4iBTCc0kL3ZFGhdHAvz7WtFf6ay/8=,tag:ibs8q6nAphKDnOB+u9Wqbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
