apiVersion: v1
data:
  KUMA_PUSH_URL: ENC[AES256_GCM,data:ozi7DFvHpYXHf66tTrYy4tQAN/M1WLhxntp37P3yTFCHrcruFDOt0t0GZkilqxuok9YyfM+OEiSqSiV8zuIyOedNC4ODZResRfXqFzl7ApGxodSy/KtduA==,iv:d8pgeU/+a3pPniP099CC560ZEdQgp2c7yRD/eqd0owU=,tag:uDD3t75m1zRHGzeotSmXYQ==,type:str]
kind: Secret
metadata:
  name: health-kuma-kuma-push
  namespace: automation
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbjQrWk5BMWN5NStjTy8v
        a2N5VjJqRGZjYkQ1TGtLcDlqTGhYdHJac0Y4CjRDM2k0aWdsUWRQS0xJV0Y4VUpF
        QWpqdkx5YlR6R1lJVjNDL0h2b3B3NVkKLS0tIHA1L0dRR0RHbFBRUlRMZ3MyZkt0
        dVJVL0dJMFAwdTZPM0JEV0VHZUFzREEKbvRoqRdOEallz1j2QQk83vmvEkV+9Ygk
        CDADOAv1Q0fHe7sKh6vuGT9Gv15Rjk67c0NcfeI7inT7sOEK+ow4vA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-06T23:58:04Z"
  mac: ENC[AES256_GCM,data:YoPA0qfXXoBrDWbQCvLfm+qBpZ9LfG7SsdqUPLMR2yqUoGQadxbuNRC6MIJX9lS5AgC9FPZNrdJGYZRPmJh/3FqN3jG/AbzsseZXjzqo4VAuf8Z4AId96KeRwi8scXRhgim+6j9f05QTMItuhNvl8MZ2ScY2x5KJ5n/nc/XOczU=,iv:Xx6FZgwHZ4ZwhbRZybgdSFW7QKq/ldAJ8bbkBWW0RaI=,tag:Qy46ocLGGR69vSYAH88qQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
