---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: arc-runner-set-rxr-cluster
spec:
  dependsOn:
    - name: arc-controller
  interval: 1h
  path: ./kubernetes/apps/actions/arc-runner-set-rxr-cluster/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: arc-runners
