apiVersion: v1
kind: Secret
metadata:
  name: autoloop-agno-auth
  namespace: automation
stringData:
  AGNO_BASIC_USER: ENC[AES256_GCM,data:NjM4XA==,iv:yJ6pgw2upkfHHG/iNKRaOsZ5bxaOP/bR8/Du+EPMV6M=,tag:P7kIvttQHcNgIdROPvIIVA==,type:str]
  AGNO_BASIC_PASS: ENC[AES256_GCM,data:h7/ICMrPIlSPUKihxJTvD0XJDHUVj8/W,iv:ZWGFm/fVJ3GRpD6u0WOa3PM7Dft2SuAyMVuJtpOvV/8=,tag:RR2mLQMBgh1mDiTcQk/pRw==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dktyZGxwcXZVb0dhblFW
        aTVkVUluV2c0c1FBSi8rVTFzU3ZickRkMWk4CmZGTEo4L1lEanVMeW15blVrc1lY
        UEVNQTBwRU5SSmtPa1JRakpCRHZNaUUKLS0tIGlHTVlYTVNtM0lmbFpFc0hGUTNi
        Z01uR2p1T1U0NVYwTlBENmVubDlyaUEKafjbvUdrqr+sPOkc7R5L2HrD6PL/nwM9
        xp+L+yzZwWmekTc7GRaKA38qRu5GbiseG/vVaoP3tjDwj5D1f3HaNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-07T20:31:59Z"
  mac: ENC[AES256_GCM,data:hZGJmkuTJirqRy3NRPVM2J/+K82KRQbzm9qMfE9E8uRtPfIgWEJ4WX8IcL0jiRcoc90hQwuzzQ3VJh8W5BogjNyF+7TuO9j3stF+71SdEpgCjHiAld1OWdJA0v4yC6MPkYgUovhPYoZvk14y3p/uxbl4iuAAoaX81v06+MPdWk0=,iv:t96h8Xve3y9d5ApcCEJ0XyUrE9vsnwX+h/JFXS6q47I=,tag:n4vo8wTmI8oV4lfu927uRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
