apiVersion: v1
kind: Secret
metadata:
  name: democratic-csi-zfs-nvmeof-2-config
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:LNt0bavkArJP9Gxlb5m2iPI9CGFBFc/KaE8f4Y+JwJ1eMl78y7O1D82vQrmTAJKRUUA1j0FoWvnT9Z8tQePlF0gNekAKyyeeKtL1POHI9skSzm6o6yqTAhPEmRpWDgk77O0cLIy+2RCeqcqyrrG3iE4YsIMivgSf4JOqvVikUtRmzMVrpv0S6G64XL/MO/s5/O3o09pcn8BMI8waJ6IPyT9A4sEzWYAEdyEVyHn3oOxQr2fFFlK4qk6oc7Evnp7JJw9VoxCLznA4n3PpsmOh24MPkt8QVLKFTp71AH2Cf1gAdzBz0yOfYVyNlQeMGn2doityZIA0s5E3nVrDLCVclYgATf2X5/fsVd+i/C4zO3xhGaVJCCCafEgDAN+kM6S8K80bQnYQRWx9XdS8PtRFlrKc2KHe44Z9HxoTrIA701eVhLSOGoGNupL/73SJH2exMDQlNB/i1LYxneydMvB0DwisZP9hSiCcq5lp4mgApcV1JO5cefomUA+KTKDMs8H0bno7WoJb+tarAvDYPPG6Q6G6QJSkfmav88MZe95Yw7bsbnZpk3wvJQNuECbJonNgWBC53eMuNfzxcPeW2rJcbNowxvlceVlAw56Lq8NW0ApgmAfBCGRTEyZ8caseVn6YOImKhMzHch2/AtO2ezPadbYtqufUCG7ZnDsn5ZexuPbNkXFrfmQke0KFAplCBwUKaL5calgt3/IQMf28ZLAZ0Zh5M5r4TMgqtu0cW9RdUSzCNtXT+HUjxtBqqWoawpxkrkFn0XiHDF3BTcolmI5MVwtRtIHOzjSJTJoz9aFfgs+rn2g65Pbm8QzJq3dlOzYz2c34Tjd1KiiZWj8RVPD4Qjv9HcgL4kBODuAisyIM0lEIPaWpEbneTGCkFltWFdRciMY4pN2krmvz0gIIMBh0c9CElna9Dl7mIG5TMhugzKrgJXBNGNNUZNNBiYTtQCIKPHefotFHZ3E+ZkH/Dff9l3PcXAYzy8LDqf7QwpJbYTlyaA5JShEIKQ/20Bb/bCEtgE8IJ0nHSkQuZtAnj7x7xcRWjvE2DhMbg3xQ48XY9G1wipanFNMflkKAP2HVq6f/5ZbkSnzXcAPQXrcL2K/S007HdG04XsiJDlDTfeUuIu1r/XhEmXjj2HpCeN08Vjei2FN8d1bQNwgoRO0+cuKGTHhNSMMKRWpiNzlxLHCO/X5Gzx775pKcDU5M2Gz09jRC3b7X3ojFCzDYkDNluhGwGPU5e+MfepP96NFY/d1o1ea+DUzYQ17CVNZQNlKDFLgzITMwCwa3mp3cl4lTO1J2etuuET+1oipdF0gPJpbT79TxnL1+sp/pXwVxyRjC20OyEZSrK/5j5d1me1fiOJFxi/PLMfx0xJpp8RuGmBIolA==,iv:ioBiOPMhkan0RHmPfZT2uSaYJ0p9ZWyejkViEok2Cks=,tag:cj3QoJHIedcCBRVsZW0EPg==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbVcyU25zY1ZCY2EwZHRD
        Y3VuTFZmL3REN2hzNmxCT294V2V0RW14d0JBCnhkRmR0Z0J2OWZjMkVXcHBZOW9n
        TVdHRTNUcTlGY2ZlelVacmkrNm9ZcDQKLS0tIHRlN1hmTUdKNmlvcitwT3BmV1Fv
        bURVaFRENGV6Nk5JS29uM0FJSDNPMWsKu+hat4CQrfIk3sR1Wzvr6d/560BpdCTM
        oHFvx81jnM1xmPOwrgQCESIGl1EY7Trf+3iYlzL3dNHCSXTW/5ydNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T14:40:50Z"
  mac: ENC[AES256_GCM,data:ncTv2DGa7ROdyVZPf0pO06MzsifhJcjA3qX8RRinlpxArwK0tZI1Fc9JrDblqwJXEPd7ytCq46tttSRmHp9UKIxNZT7leaqQyyPAZqqPc6YsfhPKnaDo658iq4AKwhVTTDNSZlDLFwr43HTE7wY5EW4cpes7294jW0Utm2gH7so=,iv:RqMFZNV9vagrG1H/tCQZ608pwKYHMyn6TSpmSb/F0gY=,tag:Zpq5m1vU+6U5R5k5Tb3gdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
