apiVersion: v1
kind: Secret
metadata:
  name: forgejo-credentials
  namespace: automation
stringData:
  FORGE_TOKEN: ENC[AES256_GCM,data:cPF98uGdmeZ+Oaleh4CCiJ6joJSw7uETd8bLrKS9I41SjIM2RXXOmQ==,iv:wmmHiHkC4ch2JtHPo+XqGR2i6SbCt7AJ7qocsqvzhAo=,tag:P3myHLJ2bCe6nm5HunXmAg==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYXVXUG1nblNoRjVnWG9V
        L056TWovQ05QTEI5QzFXdE51dFNlWFV3QjJFCml2ZTk0YU9YcjQvS1N0SHF5SGVz
        MHZ5ZG1QZThoYTJEVnV5RURINHVlalkKLS0tIGtKY0hrYjF2WmJOOThBMC85R0VO
        ODA2bDFEK3JOOE9aV0czMnNCSWNCOTgKOCYTZhj2Ti1v9MvI/zLAbBx0lQa/Lnkq
        9EMAlV94Xw1+23n4eQpurTdFAfGgxbaxZpFhxkAIWOpk0mAw0kt+Ew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-10T00:25:00Z"
  mac: ENC[AES256_GCM,data:PeOzItyqdSOTgDBYf8Q7B6urXBYh7utM+50NfBPXCmPd9NYp4vXhlh2vcDW1JyS5IQR5Usk46plOmdj7ElvjZ8fQmapPArF+8x84V1jtvD/Uwo3JTO5bLb7ogS+LUccb+DIesOs5M+mE1QMstWpD4NBQnfKS92nNGQRuV1gRyUM=,iv:J2BIY0iFdFwavDObjYiYTQ/GETckfrtpLnFafI78XBI=,tag:xtzDz4W7UIGFNhNGt87QwA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
