apiVersion: v1
kind: Secret
metadata:
    name: forgejo-credentials
    namespace: automation
stringData:
    FORGE_TOKEN: ENC[AES256_GCM,data:f114BOhiKtVZyia2+tN1MF6DTs72Z+lgBgtXi+WRQpef0QIUnze1tA==,iv:LZaCmvofX5XKZlAEJvvTNPaP+N+yeBWIH6k5gba2/b4=,tag:PFX8IVwhlAuMRAmA1rOLpA==,type:str]
    FORGE_URL: ENC[AES256_GCM,data:UPnLTUnBasBwTx1wDW1n8JCaD/UDBycoKay3UAuEAlSrAM4uIqY=,iv:RNyyL3Ii65iqwjcMCh/u8dKk6Hi/+ED7S1nxHZVRBTU=,tag:JAQGJjK1wriBLvWvQJFdcQ==,type:str]
sops:
    age:
        - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYXVXUG1nblNoRjVnWG9V
            L056TWovQ05QTEI5QzFXdE51dFNlWFV3QjJFCml2ZTk0YU9YcjQvS1N0SHF5SGVz
            MHZ5ZG1QZThoYTJEVnV5RURINHVlalkKLS0tIGtKY0hrYjF2WmJOOThBMC85R0VO
            ODA2bDFEK3JOOE9aV0czMnNCSWNCOTgKOCYTZhj2Ti1v9MvI/zLAbBx0lQa/Lnkq
            9EMAlV94Xw1+23n4eQpurTdFAfGgxbaxZpFhxkAIWOpk0mAw0kt+Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T02:20:26Z"
    mac: ENC[AES256_GCM,data:+0liPeZt799Od2K++m0jKPlmmZV19ad5kezuRLLZlc2VpBTtWVfLSdsQUTPKef1uS+Xy+Brlw33EOpHrp+IpfgqaEDmnISyGJywb+R91Vrh73gIH4yg6gMCjhHcnta1Aqf1sJVUs3+hJF4xGDDN9egEwXZm02zmrWWm397vv5ak=,iv:5/3naqzUyOeKSWOHMXvMbwHPqtga7mNy3cxCxiX/VOE=,tag:Vopel7ABosLuQPWm8gbxoQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
