apiVersion: v1
kind: Secret
metadata:
  name: memtech-credentials
  namespace: automation
stringData:
  MEMTECH_BASE_URL: ENC[AES256_GCM,data:x83KkQ4PSEuqW7vvMNIC38nAqlLKi2/QCx97QN0FlkUiGZw=,iv:P1bHcrHxc7WtSr+w1Ye384LJBZbk95+PUwCNecuT71k=,tag:zPRZZsUOsH2ncb/b7wCuiw==,type:str]
  MEMTECH_API_KEY: ENC[AES256_GCM,data:uQO3R7oykQUmT+UbQxFrrm5N+h8Z7tcuDYXnmA2YwqyCleRPvjIys9Ib7A==,iv:wwAUY54Oxfo4UypxK6+ffdBK+aqBlNW1iOBSr98W7So=,tag:RLEcmwF3hojAo2zSOimtNg==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcVhQcmU4aTZDQUJoQjAz
        Qlo3aWR6dzJxRkt1N1I1K1BFRkM0eXZQbjIwCnFsSjR5STFXV01HamhDbytwZk9r
        RG44OHJuNEVrQ2ZtWW9idnRMVjh6ZlEKLS0tIGlFcEc1SjQ3eUd0MFlHc04yRkN0
        V2s2b1FPaFJ1QldXcTZhTzg3L1ltSGcKvuCLxTHIKtwxXmfTWxB31AwgtufcsTLw
        /ohKTIK9N8c+Y+aT3Uay//a9kD8QzT31BPGA46JaeO4vGQAtsJQWeA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-10T00:01:07Z"
  mac: ENC[AES256_GCM,data:jfR0ywtUCUgr0qXcDaZWMyO8cC2A3uQepwes3dx65ShCcB60EiSNZgKNODb950ieaDOHhT2ygMMz1xkQBuhNFzkMtCxPlmc2/oMIoMFsqIlkxN7Mw5zsuMsSrMp8SnBf8nL978MdY84ReToGMcwEb57/7VYhvmGY5lLIpJYfUMc=,iv:mwhMxCLrZvnxXEYkkvmwAqdEWvsx1z0y3KaPoxa0Jv4=,tag:KwcpOJRVXF/o5qAHswhq6g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
