apiVersion: v1
kind: Secret
metadata:
    name: openwebui-credentials
    namespace: automation
stringData:
    OPENWEBUI_BASE_URL: ENC[AES256_GCM,data://uSqgVUDuNDqQ/3FA2CtGq8xKYEUC4=,iv:LwUl81VM5uNfX9VX9t6AD+nIQFrEpYNOtcmXqolyWhI=,tag:BGWmhh1OBoMLAQsNbwAXig==,type:str]
    OPENWEBUI_TOKEN: ENC[AES256_GCM,data:Ugw/dRem4kgeBwt/VGYv1fvJvHp3p+fh6z8222QgjbIscX0=,iv:tnA8i2VBY13JiU4ilopeLzS2Zw2KHqaLNnbYUZbNIIE=,tag:a/yeFc2ZQ9nQ3WcDcsIFZQ==,type:str]
    OPENWEBUI_KB_ID: ENC[AES256_GCM,data:jXk4A0oavXUPPB2edH52rx+R4isKate0eOVafYWiavo2FCtU,iv:tIZaMoYst2IKQAUAYoUO9JJvRXTXk1hfwlmmhCDIrhE=,tag:KlTSBCCj9K6HZIP8bPSdmQ==,type:str]
sops:
    age:
        - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVWVvVGwrZ0pwek1vQUpt
            ZFBrQVRaMmZubGFNbjdyR1BidjVyWHV0U1hFCkpBOHRrUmZlRXFhalBHQ29vMjNZ
            V1BpN3h3MW1adWxtcXlyczRGQ2t5Yk0KLS0tIGM3dXYvWlN3eGR6Y3QyaVlkNXMx
            U0VNcHRwRW9SNzF0c2JqRVdYck5XczQKFRC7XcvrGNB8mom5gqqUHGp0LfTiZdK7
            Nleyh/5VfJWog3JA2WpVWWbtLecWMXf0f/NQiXez5Vc+puVwe0zhlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T02:07:13Z"
    mac: ENC[AES256_GCM,data:thYa9xFpi9tnftKpJ+DUG8KkeN3HjFvGuvq8ggKrbY1wYBjgcq+YI3MTDwGb71eUJekKDOvV/wQFIf/wCX/OnEaQa79wG3Mwie3OUdUtOaywbQGwwdtkAMwn+ZbZ5vtEXkkZsZvYUpJ3e6cMjwI1cMvXxpfYbVXObG8N7QLJmRs=,iv:39V3Q5A8Cv5pxtGlFziVxhBtmEhP7Tr6t28sJep3bVg=,tag:amxQD3c275y5IT3Ez2I1rA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
