apiVersion: v1
kind: Secret
metadata:
  name: openwebui-credentials
  namespace: automation
stringData:
  OPENWEBUI_BASE_URL: ENC[AES256_GCM,data://uSqgVUDuNDqQ/3FA2CtGq8xKYEUC4=,iv:LwUl81VM5uNfX9VX9t6AD+nIQFrEpYNOtcmXqolyWhI=,tag:BGWmhh1OBoMLAQsNbwAXig==,type:str]
  OPENWEBUI_TOKEN: ENC[AES256_GCM,data:n8GgKN/3ewANzS6fSHFzLIvwX74NBABqfl2RDmJit8ctIJw=,iv:+ik13vZjeIqMRZxmUhiQGPWvePcuHKtJqBc4uC0W4Ko=,tag:RwXWid6zeUYXWnXrTrTsvg==,type:str]
  OPENWEBUI_KB_ID: ENC[AES256_GCM,data:jXk4A0oavXUPPB2edH52rx+R4isKate0eOVafYWiavo2FCtU,iv:tIZaMoYst2IKQAUAYoUO9JJvRXTXk1hfwlmmhCDIrhE=,tag:KlTSBCCj9K6HZIP8bPSdmQ==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVWVvVGwrZ0pwek1vQUpt
        ZFBrQVRaMmZubGFNbjdyR1BidjVyWHV0U1hFCkpBOHRrUmZlRXFhalBHQ29vMjNZ
        V1BpN3h3MW1adWxtcXlyczRGQ2t5Yk0KLS0tIGM3dXYvWlN3eGR6Y3QyaVlkNXMx
        U0VNcHRwRW9SNzF0c2JqRVdYck5XczQKFRC7XcvrGNB8mom5gqqUHGp0LfTiZdK7
        Nleyh/5VfJWog3JA2WpVWWbtLecWMXf0f/NQiXez5Vc+puVwe0zhlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-10T00:01:07Z"
  mac: ENC[AES256_GCM,data:3Yf8oOq+s7SdB7bQ271D+nCS9s2n8+FIWJHGBQ/v03kYMaVJ29qODRBYaEuCNZqKMXpBC8X3Qf4D13TbDV1u3iuthkoVuoDBj+G/qozC8l5GI814DY0ZD8oMTf0UH6BrqNV8M+ttnI+WFNhkyou/5JrlNSEG4E3RLAEscROoXwM=,iv:mxKZ40nNLD+sqegucGBckDoewhQLQWzEhV9gyrnFzYU=,tag:li0h2wsEK7jQ25SwI01DJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
