apiVersion: v1
kind: Secret
metadata:
  name: openwebui-credentials
  namespace: automation
stringData:
  OPENWEBUI_BASE_URL: ENC[AES256_GCM,data:uCcxCjLlrf8oD8rISqNcVdxvM72KqXo=,iv:moXLpxSWXQX3V4WobgcUz1GAq542H4gpbZN6Nqf26H8=,tag:aN+q1YOWuIHMMooaMVOkjA==,type:str]
  OPENWEBUI_TOKEN: ENC[AES256_GCM,data:7h3b8MN4rRQe3xEYMntSepJpv/328x7W3eVrHiY6q48TD4A=,iv:zAfaxCBHOnKJzCS3VfPZ+uS6dhqHI/02hi+odVivGsE=,tag:HE+5kyPDemzT4VN6OqlK8A==,type:str]
  OPENWEBUI_KB_NAME: ENC[AES256_GCM,data:vLhjlct/KUntWVQ=,iv:9fTbyUh4DVWJBDNAnHpFaPw6uj1X5XAknRxqE0PCBRw=,tag:YE6gzn9+rOKb5lGidxwIbQ==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dGkrVDVkU21tUnZsSWNQ
        b2h3SDFvMStWREowdkFoU0dZMnBqSnhGWVZjCkxxd1BMUGNtYm1VZmV4S1ZiRFUv
        U0FKdDJJbTJXYndNWXpsWUJ3V0pEVVUKLS0tIDlCdVE2Uk4rNlVadTRmbkNDeUFk
        WlZDM2NqdVp2bzJmRXlTd0Q1ZVhoeWsK4Bn4cUqlii9c7vEGsu53BKXI2uDVHOUZ
        p3pRe3r9bL4o/G8eTumpqKxMYqKnDrZtMXSTSLrcVi01aTL1UIFu4w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-11T16:02:23Z"
  mac: ENC[AES256_GCM,data:ppI5KKU+JJUPq8me6j+BJGjzZz6Zu6VbV3BdqZBwbdpHvRMLs4gGJwAoEoVgzFMhP+u7unbyIqFNyWYa+Rwxyd6nsv12L6vUk/IryP8WGlzNsPahqPPZcqZDzXEcM8uVFyPdwoMDMK6Mqatjhpk/AyphbPXj3r2aTy/UMZmExTg=,iv:i0vpiASP38OFJp2xmJ/7FzPEMShSdtFWnGc6gAL+/es=,tag:AWpAtBzcGC8Nd9lBnEed+w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
