apiVersion: v1
kind: Secret
metadata:
    name: registry-home-arpa-auth
    namespace: automation
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:7n6Loj6ssvomavElOrLnnItZuF+CVnuxapLG1Lw5XTsSqU6a2K5y+5SW8kJxfdxzoc43U8A1V97MJFdXA9WKFHeSnDiSIdGiHMfjc+b1wc21WNgVNTZb0JG/K60yfsyRsu1WER3+BbOdWZg+E0i9LKrR3fa8fecpUE4voIAK2ADmKf/nCqlnZFwAgbeCSf25FHYIrd5JsJjh/ophIThTs8X7WFut8+gMv3N4ZOPM8hkkRkwp3tUoJTn+IbF7/2Lgo0xO2Ai/SDGzeqii5szThJ7Q2A9Vq9rSclww6VC2aDYiiBxx,iv:OIi9KZHiLkYS0i3SqhcmSnNQzj6zEPQggUAR2NFuuC4=,tag:UsGyspXSlGAhvl0pieLLrQ==,type:str]
sops:
    age:
        - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoY2JQQ0dncGZSTlYvN012
            Ym9MTW1FSlZvU3RMNmZNWi8raDdUMmJYanhNCkZqU1pqNkM4clpyODMwQi9BN1ND
            d2UvdzFjSXIxM2J2WVVvQVNhdlhrNG8KLS0tIFB5M2ovT1FXOGJtSXpGT3hwS3V6
            Y1lYRVNGRGhUZDNYWWdrMUZ1aDIrbDAK4ZI+Yy0p8I8hEuERnxQvz6EI6sM8cbHC
            d9HUnlGYgjzv8P7YWrtCLr2gVr1XMocS/QgcoEKVUgAbSAVZ84dWHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T02:07:26Z"
    mac: ENC[AES256_GCM,data:DcSIegUECFmiJPAa8K+K70iJk6pDTQabn2I3jrdxERyYLDwXWK5q0Xbd+/gWbt9dpqaS7X9WnkqzaxKACKV0nHtX+XG8m65frt8WV7txMSOa0DMvgHvLDHtrB34yXmkGJ5gMyOBW8VgjtyBl61BNOsUwChNlosLSoNm/9Kjrpm4=,iv:kceM1PqyVhDh8BT3j/tivNAZJiOKHvuo71bytVm8+QA=,tag:KzN5p1J/J43z49fzxPOdNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
