apiVersion: v1
kind: Secret
metadata:
  name: registry-home-arpa-auth
  namespace: automation
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:bI1Uvi82+7nGKCdxgh3paNqPsyeg0pFNNGIAeu56igt+J4357+0eEazwBHCLQYaUsrG74qtjOWDuUr9X5hP2NNxAhYH5iwUNr6d/H0VT9OQb7id0Ahrd6xfFB9frBuCSxswN+avYdmMyJcGu6gn03rkDglVpmwpUsLDr7Q==,iv:9+kAldZNaUE7B1GME9Yo2IFQSIEFaifT2x3492dFWxQ=,tag:IWfzMdtLsaG4eojP+X8ZWQ==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoY2JQQ0dncGZSTlYvN012
        Ym9MTW1FSlZvU3RMNmZNWi8raDdUMmJYanhNCkZqU1pqNkM4clpyODMwQi9BN1ND
        d2UvdzFjSXIxM2J2WVVvQVNhdlhrNG8KLS0tIFB5M2ovT1FXOGJtSXpGT3hwS3V6
        Y1lYRVNGRGhUZDNYWWdrMUZ1aDIrbDAK4ZI+Yy0p8I8hEuERnxQvz6EI6sM8cbHC
        d9HUnlGYgjzv8P7YWrtCLr2gVr1XMocS/QgcoEKVUgAbSAVZ84dWHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T23:57:59Z"
  mac: ENC[AES256_GCM,data:OeGQtyp/4CWM/J9xbYPJhorqdKkerGRXBM1aIs/uNDOKtC+m6WGTOu5IKszc+LyqYKfSMMe0zJPzhjnPILRj3F7HliQpXWqXnZrlRMR8dLKaa83YYuCBBbdyOtm0PQnkgQsBT2K9kLkWSHKc957JIZxVxtDdZup/if+dK5bKiKo=,iv:Q8eudGg5xtxzlPsKItCpddEmG+pnDZCQy1uXM7fM5ak=,tag:Q2DfhLHM2wSet7v//8iFMA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
