apiVersion: v1
kind: Secret
metadata:
  name: hermes-peer
  namespace: automation
type: Opaque
stringData:
  API_SERVER_KEY: ENC[AES256_GCM,data:E/oojkHh8wIaDrzPLQl8X/AopIJ+TldEjlhCk9T96ZI4p9Zp3lBebcAduI9hgErtxKP/XGy+2uGPNQtkhJzhtg==,iv:vM8nw2gG/PYF8w9l0DTmiG34RrbNzfijNECFAv+Fpkg=,tag:6NJJiXB9MJJ6USAKaITY+w==,type:str]
  LITELLM_VKEY: ENC[AES256_GCM,data:a9gZYKYDHi2L5NvD19fA1cO6lIPNiP8Kmg==,iv:HgLuFX6fvr72+BbTg3YqaLRuG9/K/5lee19CuPS7+sM=,tag:WxTuBDqQuvMyDBYIg+XEaw==,type:str]
  A2A_SHIM_AUTH_TOKEN: ENC[AES256_GCM,data:vmL+TEemsdETOE/oGgN0bV6k42FC6SDbV6BQyG6wWMocnWBFm99bIWK0E0tC9lfoJSVphUvMx0w+1+8aVangxg==,iv:nsl8uAwl1VZ/ehH7JMQDI5C1rvccGwTf3eekGCx2y/w=,tag:bVW9SU1Iu/fvmHEIOTInNw==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaWlIZW9oTEZ0Z3hBRU9N
        SHNZVWJyMEtRbTlqZ0xZT3JMZU9NM0N0cGdRCkF6RCtENkpiMGp6VStMTU9rb3JM
        MVpiaGlIeU01VzJpWVVPMDhrK1ZIUW8KLS0tIEpBVklBaDZCME9PZEhBMXQ0RTZx
        d0NUcjVIek1WK3BhTFMxakVVelhrcXcK+4+Pf75B/guy2mTWalpRp6xZv5V/xKcT
        fxFBA3ZhOkPivYAajphGJEvTsBU5YDSHffJS0XZDTeqUP6BTTQrDww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-10T21:18:06Z"
  mac: ENC[AES256_GCM,data:17dSyv6COfVPhwfGtNBOnXyLR5NeWlXSW4yCniEEW1bx4SaM0wpjnqxba8FC31MHILmkdMKJmrw706NopbEpL+xXPQ4C5ZGT+btx0lANhPTLid7OXPKi29EpF9TLiCo6PNB/qPcX2fffglmkbfNrC1t3kcU9nRcjvYv+PyUAfWg=,iv:sQ6E00fk0skWLdWg/Mzk81QpiIUkJjlP3HOAzVX8xR0=,tag:DGG5C499R6eN935e8PbvbA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
