apiVersion: v1
kind: Secret
metadata:
  name: hermes-peer
  namespace: automation
type: Opaque
stringData:
  API_SERVER_KEY: ENC[AES256_GCM,data:E/oojkHh8wIaDrzPLQl8X/AopIJ+TldEjlhCk9T96ZI4p9Zp3lBebcAduI9hgErtxKP/XGy+2uGPNQtkhJzhtg==,iv:vM8nw2gG/PYF8w9l0DTmiG34RrbNzfijNECFAv+Fpkg=,tag:6NJJiXB9MJJ6USAKaITY+w==,type:str]
  LITELLM_VKEY: ENC[AES256_GCM,data:a9gZYKYDHi2L5NvD19fA1cO6lIPNiP8Kmg==,iv:HgLuFX6fvr72+BbTg3YqaLRuG9/K/5lee19CuPS7+sM=,tag:WxTuBDqQuvMyDBYIg+XEaw==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaWlIZW9oTEZ0Z3hBRU9N
        SHNZVWJyMEtRbTlqZ0xZT3JMZU9NM0N0cGdRCkF6RCtENkpiMGp6VStMTU9rb3JM
        MVpiaGlIeU01VzJpWVVPMDhrK1ZIUW8KLS0tIEpBVklBaDZCME9PZEhBMXQ0RTZx
        d0NUcjVIek1WK3BhTFMxakVVelhrcXcK+4+Pf75B/guy2mTWalpRp6xZv5V/xKcT
        fxFBA3ZhOkPivYAajphGJEvTsBU5YDSHffJS0XZDTeqUP6BTTQrDww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-09T02:46:06Z"
  mac: ENC[AES256_GCM,data:jq7fauSPS5EB+YDZcY8C8SUW7Fo5c8jq6o67reTbzp2VT0jKfCf6e2+k54PR3Whx3sA9LEwzX7NiQBkbw4BjRKwhkTe8WYUQdDwEqYNd/G9SPJf2MJqPYbiFDpynpLqQMJYlpmyMmyrZJxAThYF2hDOStEiahOPNYGmYF0I00sc=,iv:WnsK6lsPsa3eNX7NTA6PG9r15HzyYDFrT5RVXeUEuXs=,tag:rgW3kdT7Ov8M3OeUY5uDAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
