apiVersion: v1
kind: Secret
metadata:
  name: democratic-csi-zfs-nfs-1-config
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:x8sXShJ5dR2rvNF3hjXtrzbB15zlppeRbIJmYR8etDf3MW2RWH4p2WG39dA5/F03uotg4iZjkcImG/+AW9mikFtgwJQm9Tg386IXYjri/36TiVlHyZESA5EbcPYL1g5icvMbA8KXb3A9LQdxuoI0zaXhdcRQ0HlpvtcZFrgRLhlkOsNr8+3G7jmY9P48YadKyXmViTvTFvSYvHiDFng3YFGPfRSH+eZhQEmJ2BP6yptUY4kkAuTkbdrS+kYGEh+TEG2rr7Qv6qdwieTSiXCN8WhVBS2xrvd50vYEUeovOzgbcrJ13H+6LDhbqn71H/KnrAq+hK4XFj+uwUM9Ejb9Zwf28yHDTJNeJEKAEr0K3xBIuFgRAAwBNZttk28mN6qDaj9aH/AI5G4w7w1kjHnsLuHBAPafYgnMfJ6DgFQEb/C2bkFlCNWmrvXvowMiHIBSg0m3GK9+CReZdW6qGfEybDe7ddT93EzQhQQO+R5bB9TLGnHAD/6vmoaG84HOCmYG0jZSfkV4pH0yfHeVWzw3qjwOMCKDutpJfSbknPDoPEhP2+6TAXJ+EpilGr7DiVOxjGz+bF6PHbXtWkedY0H+pKikdiuXzCE63HPA6v6SqTHiuLT1GhF6v5DW8oJFxAPLMpzS0IiFe82oX0MkDxjma67N0D328MSuh2EEfN6tTwC6q8H6yl0ExmmbXpKzZ5TLI6UINZqcXycsKgQ6r6YoKd2+x7YDEVqrfq9shl7ay/L3B7aXnxw/hVKlGB8yC70JJj1VBiCZ9IbWaStciolIgt0ixqRtfTRLygJZsIm7NNVzpXL+p18R70QxYYxc8LR+tWjN6pP3nGKbT7KwbhyaD1eilSIyRsVLRHColYYJXC8Eq7OTEQYrUHqNJab/1/ObeMv79rxLgPo588YoxnNaVkznWSL/v9ddRSGMBrU+IBOaquV5WopZVqLd+Sf8rpWEFhvVfmooG8FMXpPXwwjA3DGPHbPufycnpOf+PLZRIH0ZkLlm+vP5WIw50D46W+YFTHuu9/QONgqePdVj6kmNGafhZHTAQKiFP74seSsP0uDcQ5lzWPjmxxFDTlU+tK4ubhEeMiNZ3yul5S0s8qd4mV3ZTVp82lJknwrAo8UrQ3O+bfIqrOpWJ+Oy4O9Kl3c6yDXnWAnysrr/rXwd6ZXKSCJe/pO3KpZ37odJrNP7dGzR+IwcREUyWTJkJyHriS3lT1SRXR8ESdNFEiEoF4jRgcxm9XLJAkehQW1nVN0ZHLkpFwt1dEArc92KSaHYVb++Isv6exCFs2vicqpIs1hP5PRQqzIjiYTo6NcZcK+kkgnX,iv:NBFJQmNJVaUDPyXFnp5Koe5L0sWktecXqqeJ6Zt+o9U=,tag:cAkJCd0TPcSsWBfSj0eKEA==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMY1VNcXVVUzVPZ2orMWQw
        Zlp6bTFrV2kwOHhyYUNLYW03cUxBR1NsaG44Cmh1bFpUV1MxV01tOXRycmJQVisv
        SHVyRzRQeVEzN0dWWTg5S0UyL3FqRmcKLS0tIEwzbnQxMGhkVXdiTW80czVjMity
        eHFtV1ZLTEQ3bWNoZzd4ZjI0eUJOL1kKlDpSlSfpxD7LOGNHEtLd4+dtPolZ5/EW
        FU5D8fbpwlGC0jOXSaxX0cD07XiANI/p8Kdl+ZWz0t8tFGwktrQfRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-02T23:25:42Z"
  mac: ENC[AES256_GCM,data:q0U9Isgi1SRXF5zriW3uBXtEriy4qbieUbDeT0c9T9DL8QrI91yhQ5gXMJuRSJi4L5NvFTNpkza6GWxro4fKOn+IFvbsNjtF9fmD//rdsQ+MgxabOdGDhFPy7I/a+iR16fbou3C8a4cudYpxOyjKvyUlXsvzk+a7A3gSe8s+9Z8=,iv:c1GUWvTVTv3GDa9u1RjA+cBZcG8JWzXYeACjxM2Dl3A=,tag:r+n88qU4Ml4AF+Mt1mP0nA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
