apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:HXh9gOUFImuFV+TXPDIR03wC3oHFK08OKna70ZZOYoaEoFhLL70elIZ7CUZzhPqxPnEdU7w=,iv:aAwYLe3YKKtuG0HfG6j/wUz1u3WNSK4Wbs5qrFqv6ss=,tag:9UB+hnR6p1aPCj+Sv6MaBA==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZHpLSWpnZFF6enpSemxV
        ODBIRDRmT28wY2FBakZxSTZHbGhxdlZyd1hzClowL3kzcGM0L0NoenJFVEwweVk0
        WWYxbFE1VmVWWldZOFQ2Q3VNc2NlVncKLS0tIFByR25UdzNXZXVIWHU1cytNYzFh
        YXZ0eXh4NlZkWHYrWVZiZkxJV013UjgKjW4OL/4807RbkrtrQ6AkuPIqGLnN2dz3
        dN9HNQ23aNm/D8RCOXyhuTNuOgcdisz92wO/cukySxj7U0DeuHB6qw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T12:47:16Z"
  mac: ENC[AES256_GCM,data:Iuu3Vp1NEz1ZXOC6OeiPKmR0siOeUvUSy9e4BAvrPjkZYFDPGXrdTpXgcr92c0hwQ5kZEVatk8sag5EDIZUkS96w2DuzJokcQxnESgolP0s7rYrBT1XdUEIaKAMn1emuezK3Vn5ozfN0iwk/e4bZ87CV0ZFiJ8+tMBcTHlIEENc=,iv:YfhWg2SxeeOO8aKJ/XGxfrF4bdwpxWia1CeP2vomz8c=,tag:b8OE6Z3iI+QscSKSosNj0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
