apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:3iIaOP761qv3W9MJxqvnwqa/WEXkbfh1LhdWn7ow8vZQ1ggGOx8ql7p87R7O8zKOzd9iTuQ=,iv:LAeD+NqvJYAJueU/AX0TfsevZKYLefgNPUZFdn67S/Q=,tag:9ATXQQt1FwBshLA3LJZfbA==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYzVLSENuN2EzUkZFbDhO
        SWoyNU5uc2Z4bi81MTlCK0QwdTVlNDdXQ2ljCjhwMmMzYVZYQnNrZmtUQTMxaGV6
        Q3IwZUtLY2RvUUZBUUV5cXU3a1pXcjQKLS0tIHR5eUVoSUw4Yk9ibktxTkR2Viti
        RlpvdktseFJuK1dob1FsYjhNU2tITzAKs9HUpQOrlGNZOxcjO2Um1auwz33sXigW
        xjXHGkwHWGmk4SaZYmpll3gJM2plXUqAsC8GLxFEwHJeiDGz4SPZmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-07T23:58:21Z"
  mac: ENC[AES256_GCM,data:T93n+4m714tUwDjhowZfskduSfUkuYl4sTcEyrRhuu9cO0Qxdtgo41iUtoePn1CyvluWKJ84g2rPrOK2HZxCCiM2WxNOBF/zRCb7dyDGnTl2T+knqpeJlfQRbLJeXBEcBs/bGkwkmzVgIzeT+DDwDR64lVjMp3+bqSkUagwnNDM=,iv:sNbmmozTDVvYOiMBUuFDMrsssjNnpHORdUFUrEku4J0=,tag:dSRfD1Lh1Vpam7bWOgeZmA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
