apiVersion: v1
kind: Secret
metadata:
  name: dagu-dags-ssh
  namespace: automation
type: Opaque
stringData:
  ssh-key: ENC[AES256_GCM,data:mxflgUzXJeC9Rhykjmt5y/TeyCXc/peLE7FYwxhSUbzdtVbTGApMTeJPDilJfbmqeGc62X/I+lq6KyDkLtO5WQZm7uZ9nGrmxcENUBtkhp31ivnG3uUk3CS1EJ4U2nmAnJ4r5wKa53t0EMRuwlYoiioq5QHOVto+LGQNcnN0hOCZH4ejYxeolTQx2NRhbWx4o7Xm1D+yr2/0c/RlUFML8ngfoU6+9n2+0NkAngGIlGzo+dwcGlmN4ZmMpmZTpMVjD6EPWkZ8PQQV5aoxss9IzoTiBMm/Fq9+VQW40hPlxlL0eIIHIfSSkwlWS7TXqHk5bwHaiP9o31pj9ZqIY1Wtfacsx1Lb2nSTjFLJsp6OrBuf8S17G5fw6+ZgfGNjcBH0k1IktJ8C6cLa/Yl3+wcOAjdthP6KrL921AVWFaFpjEKQ7kq+WH1p4JfubTTMZ0EWrcLQRN2tkiIVBJQEiQWfSh34GCR1gir2IWOtW8KjA8lq4QSY1/pruB2wInZ3TzckgXN9k4gW/LrTTlmbHFd4/2AS+fsznEaLL86Q/A85N86CaPcOTzkHUJ0DIrimKKXLLQP6OYy+pop06Hg/ORguPvg0hdE=,iv:jINATOfpCcb/L/WV+NL48DJPePSjVGJC76RtPL1UcVk=,tag:1LmX8q0NdKjHYK1FUcBSMA==,type:str]
  known_hosts: ENC[AES256_GCM,data:cnAMsJOJbJ5HLIt00xg/mUgWBftehuZgAS1djGYEAAExjmk/dv6EFGRwOsLfzT4A9+lTQj/BV/DAmN7gPQzAm4RmPaXGMh0gcC/3pVbuzEU8V+up4O/CFgqOjMA+/z6Q,iv:IRk0xeYg9FSG3vgphtV3ud6o7iMfaXitHiV2T+XTwYM=,tag:iSlM0Uifc3JWV25J+SseNA==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdHp5c0swTXYzVmtvUXdr
        Z0ZSMzZIQVk0NGM4cnh2NnhCSTB0dHVLSFNnCk1yMGg4REg5V1ZWN0V4MGN5Q1JF
        VXY2VXVjcytvL1dKR2ZUQ0kyRm56MlEKLS0tIElKalE0UlI5bWhvdjNIK3Zwa1RE
        NnQxOXoyTHRWcUhmbnlGUmRDQmtmbVUKjwxSHK1MtqJOpPhqr9E1Oj8R7NsrYmNA
        Inhu32SXjplUlLgvIMUvvVoSEwQlHZyL+tXkjrhRfH5hUT38AJ7XJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-11T12:03:58Z"
  mac: ENC[AES256_GCM,data:H0K9i/9LOcPHkPkCmWwNE46yskkBNRtUd9U2cWn6kSroGn3aRVw7cDyhgZIVXVqjzvsQJHvDX4ha5KU5pADBWkimPJQNZS7sLE+KfGjqFZ5JxF8rLzAqjWIMIA71i1t0G9C/ouzqr2fSx+T99O6DktivZ0Sp4LTbG0YxVMff0/8=,iv:AqPohZJ+pWf6vle9bcfh5mz0QVEXw+Ns2SBdnQL+/js=,tag:Im3YEqoYUFqMRCpqTH24yA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
