apiVersion: v1
kind: Secret
metadata:
  name: litellm-dagu-steward-key
  namespace: automation
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:FOBdH0Hqm+Bcrde/AFZVltx9p5gMJ8mjCg==,iv:Jr8pkTYez06DrRY5KXV7Vl37duy727m6FhXbb2ESiXc=,tag:TlTQ199YMD2XpJaDr8SlCw==,type:str]
  endpoint: ENC[AES256_GCM,data:RVzaocRu3X8LfYzco2gj62Bm5WxVOXbSJIG+q5QQ//Y=,iv:iFHfcjI/Xxi6RGI1talHJwE/JQ/TqyeSVIkaH8LE1Mg=,tag:zSTPsWFp78f5poUa5QPnSg==,type:str]
  model: ENC[AES256_GCM,data:wYl8b3TN,iv:g8nODRlANyylm4H4AAXncstWlMUYUyKsCyjcLgJBW5A=,tag:hXn2LXwHSL+5R4pxCZW+Sg==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZVRlck96KytEbTRSOVJJ
        ZWRIV3RUaGJEbkU4ekQwVDRFelZwcFpEWGtRCnRZcS9XUG43T3o1ME01d2tWc0dj
        ZmxweWljbGxycldQWGwvbVVUdGlzZDQKLS0tIDAxNzNuemo5ZkhmRTV5REtUUm5q
        K0o0YTFtakpaWm5NaDd3STNoSElSQ0UKUJMMd6W1hVKrQ1dCVAt8lNFrjMETc8uk
        ZjwGfEK5hNrUR1D9XFPFvtLrjQHQeaNAapnJ8EUtxeBOLhZ2Wu8Mkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-14T11:36:28Z"
  mac: ENC[AES256_GCM,data:0cWVpxaVbmYMtNYK2ueIkVmXF7/wlj7U5j4GY0pA1zOkWTZPIbmYXsfriabAS/10IVw5hC6NXWibGzL6muJyF6XymjSaFuCDqPrkE55iLLha9ohFqF7vTPTQfyRrGJhKVnKU+Mter6KLEop0QmRVprFI5x452a+xWOkwPU1qx5g=,iv:FSzQ0Bd8h+V7/AmFgEntJwI2dOMNFYSyZ4L1Wu767c0=,tag:qkYNHgxyqS6OfE6qd5e2gg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
