apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3pXi2SwmZlYN,iv:gS0rVkU5xQVBB5ZwPc7afCA1tgYf2bWJ8msz6TuIVe8=,tag:ZWNsABy/UWsvKk4CT/TKXw==,type:str]
    REGISTRY_BASE: ENC[AES256_GCM,data:IOTjMxC5bgqo9DKFFv48j5s+wMKm6zY=,iv:w2QlgFCY/oThxGFjiKhZoQDwLkciJONmpUgGau6k7QA=,tag:LyqWgED91Oql2iyxjWDEWw==,type:str]
    NTFY_URL: ENC[AES256_GCM,data:JEu/9SXRdqPEbHZP7OEU/A+FxIHMQhdjYOs=,iv:HYsK6Yrcuy+cIcWh+Si3G4yVA28Em1b2i4IqUPpm664=,tag:0zBb5qmMU2w+2Cc5itJVtQ==,type:str]
sops:
    age:
        - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZUxZSThHbUlXTFQ4cXZn
            TTBUZHplZitXUnV2dEJhTEMrTjA4WjBBUWpjCkVjVTArRWpFNGlUZVdHZHloUUlZ
            RTdZbmNQN0lTaEhnc2ZPVDJFVjlsdDQKLS0tIHBJY3BRaXZhbDROajVuNkVUUE14
            YVU5L1pYWkZQazU3V1F0SGtNTVNNT3MKHnnzanpNkJRXXNUmOKgpYcWH7Ge09Hfl
            0U/ju+CzaNHO4FXv6faBCrO2PvBLcNVY8V8IDL7wDfUmq1T0CjxSpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T02:23:15Z"
    mac: ENC[AES256_GCM,data:xN8MYjg6zDPq8qFz9n6W+iJ3lnlGTbUXdesBU4nznb4+DnGUfcr/cMx1G8mi+i2fLZMCKeRXlld9Q+FSzENyOJNQuG7rj5qX1//mnuLvRGgQ4gMe4jGkt8icZlKQplkyRasQyg4rLVIACUqA3P/fRUuq327V85iP7g/AzZN8Og0=,iv:ESOpAyqDey/QmH12uvnJue0fwfoYMdSDiUVL6/9I4yY=,tag:O+41K9aQOXr2qqQJsJLPSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
