apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:3pXi2SwmZlYN,iv:gS0rVkU5xQVBB5ZwPc7afCA1tgYf2bWJ8msz6TuIVe8=,tag:ZWNsABy/UWsvKk4CT/TKXw==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZUxZSThHbUlXTFQ4cXZn
        TTBUZHplZitXUnV2dEJhTEMrTjA4WjBBUWpjCkVjVTArRWpFNGlUZVdHZHloUUlZ
        RTdZbmNQN0lTaEhnc2ZPVDJFVjlsdDQKLS0tIHBJY3BRaXZhbDROajVuNkVUUE14
        YVU5L1pYWkZQazU3V1F0SGtNTVNNT3MKHnnzanpNkJRXXNUmOKgpYcWH7Ge09Hfl
        0U/ju+CzaNHO4FXv6faBCrO2PvBLcNVY8V8IDL7wDfUmq1T0CjxSpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T12:47:16Z"
  mac: ENC[AES256_GCM,data:Rs9F45SQEnkKJWUEk+KE7/LiyPWkjcGJVzzW7tDLYOH9p06uk2N0eLgW+aioBM9VY0wE9O+06v0eRcAiKxFFb/hBdETWINJc6bMrs4GBy/piqQRpPyWT+lHW4/qCDAV6R9yYiv2BaLVPchKVIv6qMDFmSqFA//LG8z6T0V3mNDA=,iv:P9qDNVEHtD1zXiZBzP9flUY8BAvW0oThgcLS9oKDYY4=,tag:V80G4NCBEtgDwk2cWVuNrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
