apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:RtcFW++vnsCd,iv:HkdnDNO1/FsZnvi4M9RklZUlW2pLsGKMgRTntyS+R5E=,tag:mwA/OdEzhwmgZeYx2OUNfA==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaWNiekVzQXVGR3dwUVE0
        SDJYK29oWVJLdnlWOVpvaGJ0MTVVVzI2SjA0ClBFU3V5c1diYzk0ampGam5mQUls
        ZStSd2JOTHB3UDBVQkUzRWxCT3l4VUEKLS0tIGdaS0lTSkh1MjFpejNIVFI0alVL
        d2V0WXVHU2pqSHBlNmxkZGluR0ZZeGcKsDJ8wECF5kij57jyYPFauCRMgHb5v6JJ
        M0vqu7d+KBd+BZht+3K94/BkQBQD6dct7R/Xq4LWELZ9rX8hgacCOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-07T23:58:21Z"
  mac: ENC[AES256_GCM,data:JNx6jZ0EFcMKeOivDEwoJJ+kyoP/SuUkWHYUVwAvgytJweBoe7OfAdv7ISyRtmmalEKvKLXGdM1tL4Qej+HSRw86b1jnO52j8SKm0cB22yUJrQIZR7il9P8PoBklZNoUHcF5udNUoPig0kLj17vo9oOlUFNq2hrprqAPwIEuf+s=,iv:WWP1QAIqNlnpWIMMNA70oxzIvw55In9ygtsk51lm6+o=,tag:SB3ofgzzZ8xVDKHGnf2HhQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
