apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:MCHT8nTHX8jnjx76xL7rJsCVcuB4qibd/HqyR24j5/Y=,iv:KSJAzGEAOoylmg0vhyrVF5mhhm/ufdjfVd57fN+G3f8=,tag:T4Vm4kpb7kYsRqDqpmCNVA==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4alFHWEt1ZnVwYlZ4OE9F
        disvZ2h4T05GODl6Zm5DWTB5RUNrYnAveHlJCjVRQXZXTUI2Y3d5c1FVOWZETzYz
        eTdzOGsyNzhRSzVPT2ZxcjJmWHhKbW8KLS0tIEp1b1JBQ3IzVHd4blNFM3JZUmp5
        U0d0MWJ3enRrYTdwU3ZRcnFidmJtN2sKJ7gyJXq2ttnUf1lyDUOVMzw8pTvN9yrx
        zd3mrz1bgwlFwmcM7wKcTzcqxGyosLrrV/GG0H/ceTdH9qjAQr46Iw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-07T23:58:21Z"
  mac: ENC[AES256_GCM,data:0tnmeQpQ7wnnSECfuSmj8uB38HcX4SVJg1y4DfcQrCYuwiqAeGpW5ARm1vMh3Tn31tE0n7U/aB2Go7esU3pTFNu2u88mD//i2VC9xtgdcxwmzGQkuHKcXstvGpQu2JmDPSSGGPy9QdpBVEczhgI3wC1Cq6cAt0/pGnk0GtjHO34=,iv:RIT9cgHzdwpXU2qrErxkF5GkTRP/11tnqQTBIa15yOs=,tag:oayqbavjnbPreH8B1HBA1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
