apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ej66Spv7xxiIeG1Nt8sJS191BqcBgU6jDYepftJqGQg=,iv:YCn5u9Kvq7ADpakhNuaZDxHANYMSJ3bmkoez/XCi6P8=,tag:UTb/trTomx8DbDr6dXiJdg==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxY1JGQWJTY2htVjVSNE9r
        V0pzL3NrcFFzMUNQUWMwMmFJUGJMYzFGN200CkJwMVBqSWpGY3E5dHFVbDJ5VEQr
        MnhqWGh4TkpwL0srQjh0M0U0dHRRVHMKLS0tIEVtdGc4d2QyT1JjWVprUzhvSVFp
        clNINytHZTZoMjV2WkJ3ZW12TjB4L3MKLeEPXo1lWDutqlUmN+5levTRcgzWhgss
        v5CxVD22xHMn9swH2S6/A3ikvZRqLn7KP96oCIKjDVSOYubEOYkKng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T12:47:16Z"
  mac: ENC[AES256_GCM,data:HuFZBRkM85N+lutOz462DOvh4Ty80bOqT8qlFpsTc0OnCywsZB8pa6UxOGxWp0OHK/cDbgf0JS496vzHqNdYdT3AXhNky9fG/8D995zNd0MXo8PMlxK86M0mBvMvcMFeVgvYSgh0ikwlqIX30atvecS37NHvuIj5H6/iemT5Qq0=,iv:ZwRApjqMtlj57fytCpJT8IXhqWyPTJq4H2+Nm/uwZmk=,tag:uiSOK1DWgcqoyfLdbJYB9A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
