apiVersion: v1
kind: Secret
metadata:
  name: estate-sweep-deploy-key
  namespace: automation
type: Opaque
stringData:
  id_ed25519: ENC[AES256_GCM,data:h7wQDzKVMIPI5tVSDmIve3Bdg/9U0AOKo3lWlGiuGnLPpTKQ+52H0/t5Fz1pRGJUQsdxAVSp1W+0EcsSSmU8lNP2rfpSfWZvRT+uy40qU0kuGJ6fqcggBVYH9+HJORPIaAkwjCYDCIlBb0aDlNZYq7no08gC+aEz6sDuDYsW4bfpm3mXqceelSPM/9mau5uqlOXabAOxvY+5VHOFexLc0Ezu1U56FMFn7u5SP5czZ/mWJQ2AN20gRgvefiLi1vyZonL5mnGNfofA7BxAtE2VWGUguRDvcQ4gavVL6w9FJkSWnd2gV9G+2BbidRKR6/TNu/K/Fmp4jgwVWF8Cy1jKqRexV9D3PMjry7dV7HxXwiSAQrMIOeSvKr/4uhLklrpL7o6SUDA8Jh6sqhYi7a4eF5rW3c4NnLxapHsoxHenEOt/E6IIu24E0Io9PCIi35aTYX7yb+rI7vpZ/L+HpI6c9D0ggtrdQOp0DbTHWlwuKZya9GeyiblTYEyKm8LpegJACgnclxRpYgEFHX3LihvvPFKfMDeDCQNPXdYgMKYEZYP04GmFIGf/eNF0VS7Dk9Ea,iv:xN4JJxFOUDy05fiqnBdWZ+67cLZGQ91n6sJEasTjkl8=,tag:icf8FprZysJVEmCq0vir6w==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VUlqL3RzZ1ZCaUx5SjBD
        WEJrSVpRTjlmN1N3aTZjR2owN1l4OEU3OG5RCldnV0pScHJLUVJIZG9EUTR4L252
        aE5ka2J1RzA5UFFxMnp0U0VCOVA0MFkKLS0tIFdrSmNQQXRSUytPVlhnS3llZ2I5
        WWFtSjQ4dXdyQXhvdlVRWTlpdzh0aTAKiqsF6HP1t63n4CTf4ULuMg0pR8lTx/DD
        cJbd+ASCPJ87GE7PzrnDg6ADXy6chmQW3gMWCiMoULZ3RNdc8Q8L6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T22:57:36Z"
  mac: ENC[AES256_GCM,data:y/Q+Fsmo6yDt/EgGy4xeBQOtURJYd9riZxnfmUcZSPXuiB50+KhzXHgE5W4HlPft7MeF7+dq4dfHyYcF/ti+Q6C3BCBqeLJRw22nIwgC3WJCudnQ+NyXVfr0AgKYeV3m+jLIZw7FkEYznzC2F9HmkYFJESnvpJcd8wjSaRceJW8=,iv:jaAFIPnsolPSrCkPEHNUX4kqKYMq0ZDIGzS6ubEpX/o=,tag:tlLMd3QGaMKzNZEBXDjI4w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
