apiVersion: v1
kind: Secret
metadata:
  name: estate-sweep-engram
  namespace: automation
type: Opaque
stringData:
  ENGRAM_HTTP_TOKEN: ENC[AES256_GCM,data:ntYg8aM28oBZnqx2Bm6Rnq+8H+sS+5F1M/F0A5riccfLdc6+aiWtLg==,iv:IozFMlhHRW4DklaFzImIHjk6JD3ShqHyVRZ5mqBbd3Y=,tag:jmDU6/jprSkY4QUG11s1zg==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcUZyMm5sUDIvWlNxcWZU
        ZDdmZ1ovenVRVGNiK1hQRzRqR2I1REJNQVhNCnB4UVdBMURyRTlwQWdybXh3ckh4
        cGlKQytHM3ViSkI5TUJ0R3VFYy9Xa3MKLS0tIEpBbTczTU1Zc215dHhYaXNUdnFo
        b3dpUUxSeUlYeHNXVTBtQ1lzOHN4eDAKq0rysNS305+4jaoN5bsP3ymk8JDa5Zi3
        wLk1IjpaJYC2YdGtFxAGukMuADj5r+kt0mV/e8UJ+64B+35tc+PVMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T22:57:23Z"
  mac: ENC[AES256_GCM,data:6qSpxrdc+vGq634P1bDWgTfBfvpmhfIwzNdQEuFiw2m84mV8Yk9wy42g71Vk5gSuKrFrouloQdzbxoqAWCvaa/QbXgPuwIKuogCZsZd8uoOQOVBTj+8+hn+v1dR6IsaZkEPYBpRWamKV1fUpQhmVBm5TUTI+Gs0pl3UxxNL6EW4=,iv:7PylvRKTgNowApTaDKRv1cLlPPwfzsSyHIUXquH6rag=,tag:edywnFlqCnlWPwp1X8LPsA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
