apiVersion: v1
kind: Secret
metadata:
  name: estate-sweep-kuma
  namespace: automation
type: Opaque
stringData:
  KUMA_PUSH_URL: ENC[AES256_GCM,data:liNuPCx0+9HAoPUfOAOnRxvOyJabHH9UR0Em4wPRoNAlBQTnkfFttefTALJUKbDVYzd/4KQ2uMt3qv1N3MylTsjS,iv:H6PQR1AcirNifUW27MoWveuAMsqGB9e8xV1DVszJ7BQ=,tag:0FqlOKXWYgSdM+GnK3I2kQ==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeXR4NG4xeW95MmpXck5q
        U1cvQzRrQmd1alAzTXZ2ajR6OVhGd0tQY1JNCi85b2NVVlBnS3c4eG8ydzVQZG1C
        czZRQkhJa3ViSXAyOG81TElBaU02eTQKLS0tIHpBUWZPSXVZNHllNk1Fb1lHTXdB
        eDZwQWFURHo3Z0F1d085R2hGc29aTW8KaXxI5697k5I3QrSUVt4N5bmitGszAORf
        s3mBtHC2u/TgMcWNnUIRN2LRxKPwemxTaA3c5vjmxdy7iGF9HFHzSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T22:57:23Z"
  mac: ENC[AES256_GCM,data:KE8yqwr2uF0bzBKaoCsUH/boMX0xKQHCHTvCYX+iaavbQSPWllLNGHlHTi6s0CXDJWJWz7sWNKxvdOnEmJrbhstPYUys2WwcBgC1TjH4Nl0w4iwG59lQZbUCLntSK0dSBt7+Q/LIvRJ+kXpgtAlRhN9FIIS8WSbgKfWfqLiGkEM=,iv:Cxmj/xXwzDoZr5lmvdHSPdPuO4RWoBdFjioQllh9D9s=,tag:/nevXdYqVVNA+1WqcuIyDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
