apiVersion: v1
kind: Secret
metadata:
  name: estate-sweep-litellm
  namespace: automation
type: Opaque
stringData:
  LITELLM_VKEY: ENC[AES256_GCM,data:ilL5ZKc34dDYBoS4hgpuTz5ThKCS5jawDw==,iv:u8nmMV7hcF0oEswaO4ESywzDLsDHWtZWo+nvi8K5bCg=,tag:mfEN9pwuNf5sEgLByGA+CQ==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTGhXQysxR2Q4UUVzWlEr
        K0lVV0ZhQnlzaFlNejBzalJqRUJhWnQ1alhJCnZ0WklVQWZkSHhJQzQyREpXWEFB
        MDBSdHV1dk5HcjNka0hKZ0gvTVRjWjgKLS0tIDRjb1FFbys2K3ZWQnpLSFJqa0JB
        RTBUeXVoVzMwckFtSEpqZFEveHFSdWsKaZtkNI2K32IztUHqkLeVK/p3SpqrtYun
        sR1eEfQ8aDQKU754aFqQoIYoJLSJknAW8YOhld7UwSXIL9HbYoVlUQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T22:57:23Z"
  mac: ENC[AES256_GCM,data:+k4P8PS1GYPfDJxKiZAPM+ujkbg4jhLjD7stZBGEO7y/jeen9xAf4XK8eD4n//DerqoDRlFC76lIeH1PTiOcOItni4DhL7uxlocM2xikIiy8PsgaNyU3rX0h5YEkO4N9mTg2xuebl1UhrqW5zeTaKkIVBmYvXFGsWhFVbWqj7XM=,iv:wvTUWbTOK9Z9E12sj0tBB2+w4SpF69hQ7DL9AMPC4/o=,tag:hS2uqf4AqhKOD1ECetHYyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
