apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: observability
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:+6UnLh2ml8HUbFuqFPkbzFPaXb5mqFtLA7meUaZKhpk=,iv:7QAj9enpuSb3yS439lvXM/TkRiVA9rPm2QOYC/hbNzo=,tag:pHlKIqU+1uc7AqapNrlktg==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLekFSWERxOWROYzFkM3Fy
        Mmo0N0JjS1NwTW5TRGlhZjFER21ZVWZIcEVRCnpybmhTRHp2dWdIMWZpZTk3aFh6
        aXNIQVhOWklBcHJLU3Y2UTc5MEdpNXMKLS0tIHgweXNkOW9RVk9zdGtUMm5uSmZo
        a3B5N2o1UGwzbURpakNFckpjbmwxa2cK0xpfuajfOcNb+h0igEIIHjYIDFuK2Qf+
        +pb2M8BsO0VXzyYVx9jFTKVKTUHCvakIMZ2dzuM0fLZeJNd3PvwBXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-18T17:16:41Z"
  mac: ENC[AES256_GCM,data:9nPUwVTrZCFYbpJKbk40PCJOiDs3Ebi8qg5RqNonCZSTSJlycPYfSiLW8zotmArmiIMweoE1gYfCZ+Lz/Resoleail+z0AVW6ELVZYYwjGrW9dmQZGM2gpZiGPTxOSX8QW3q+jQA3RNROOiRA5K33wN9Mb6b6zXyTswKbTZkyv0=,iv:EXl/n0ORpq/gE9q7svYqyvFw5JK5oevUcBYOkj0tGU4=,tag:edSI2EzZRT0bqfdjO2uvZA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
