apiVersion: v1
kind: Secret
metadata:
  name: memory-loop-forgejo
  namespace: automation
stringData:
  dev-token: ENC[AES256_GCM,data:Aq7i4vPXCh/yftHaezfQu8rhtFM7tOK35tkohF62y2Fgu9nTtjwZGQ==,iv:y8r2Q5sEuavEaYfOyG1IB+rLkS7lgBA605tjzTd+fps=,tag:Ipb8KHqKINT3yZdGCHk4oA==,type:str]
  iac-token: ENC[AES256_GCM,data:iMo7T1JZpcRnEXqar2d4k0AIol6T2icRPx4qlsRiH05Ej4XgHihyLg==,iv:hFeO/oRN6nGHd05ALTU+CCvF1wwNU2fjIjVwu3jfG1U=,tag:I09noCdpxZirjWBb76xb0g==,type:str]
type: Opaque
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRGtxYWphaHFHOHNSZnJZ
        VURKK3FHVC85Z2w5bHMwNVN0MDlGTHF3VkQ4CnE5elpwRnpNZU5SdGJUck4xeFRI
        ZDBXdEl1UEU2dHdvdDk2eVRQSzA2RGsKLS0tIEVZYjVtMW5nbHhJOStSU0FNdy9t
        S1FCK3F5bEd1RzZGZ0ZtRUtPSlN1aUEKG8+wTJftOgN/bcfCue7BMoSzE5z3WukO
        P0ANNwDLBoe3JG2Xrxq+1Pj5xjtKhrFAkvfU6+ivlF4YCJV3zFvo/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-12T15:05:36Z"
  mac: ENC[AES256_GCM,data:xYbwVzMzmpyYhOmmUJSLqFcpmti43Ht6UMlKt4+yfC1W3ObvOVxX9X9tbHgfChC+TFar40dCUkCqGYGc3DB8A+SM5fXxPOmNccmyDyHBEQoeexq6GG/HF1xUoy1tiAEYW0944kmmvulQZR04FRv/mm1t0n3D1PAlZrglIXsAYIs=,iv:Xnkd9oQkeNGRtbZTt+qwIOlbrb5TssKqThYLGQAPvLM=,tag:Pa3bHpPXPUnq8r8JzDHDpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
