apiVersion: v1
kind: Secret
metadata:
  name: memory-loop-beads
  namespace: automation
stringData:
  dolt-password: ENC[AES256_GCM,data:P4kvTmVs6f7AQOOcHSvFff5lw3Kkf0esPqiXQ8+pksBJCtiGfzAOB4NnYV7uLXCWGtA7MPBswN0jhWWtHt4zYA==,iv:098PvYHRf33BKJr9AGZS2qVAw9hNFJ88UE7c4B97j7M=,tag:cgE/hLV7TlJsT2q5lbj3ZQ==,type:str]
  metadata.json: ENC[AES256_GCM,data:Nm12yNDndCd57FCRaV5gqighbayqUxA7xpjYFDi3Awnmk/JPeBCkJIMqyg2S5GCka+DA8rpA2Ga5H69LTYwk7tvwZzRIccvWidM0W/iEIqPjHQe76revCmfOSCLXl+vAVlQuZmvyQk0WzYPQ7VUdwqc03YdbWd2dDGUQU88JMv/v99gAsAfvHz5JKYS0/onfOFFA7NU302C9Ygo/YoboLniDYXEnjxgP7BXvIHWCmaXWGF/Hwy9rhtwvKJnVRyZS,iv:lVjh6QsLNCZl4gN2SywRwKAXeU2NJ49RNibcJl5OuxU=,tag:v5ZiiGNJ5Nla6S3DyiNJIQ==,type:str]
type: Opaque
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZ0FXM2FmdTlVdDVYZjIw
        TGpBTlBDQUVJUXY4eFZLYXNRTXpCTVNNbUZvClNuL3dkNUErMzkvcWhaMWtsTWFj
        WXBWNHV5V2srb3MwdnpLUDFnNE5hTDgKLS0tIDJRZmdvRnk0Uk1NOU16bzlpc1Y5
        MTNTdisvY3h4SlFDT1B1My9HbVlWczgKNxHw2emAj3PZ3A6xIyLmxnU55pX4DOIC
        WsRvdlX3bmhkI6vU36qJhfxJJzQDN+lU+TvgcnqVAjFZq5TyU3dPng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-12T15:05:36Z"
  mac: ENC[AES256_GCM,data:hWIk3LUNNuhYU15FBS7q2hwZagzkc90tmKPSypvQrc+TjJB91O0SGPulSE2JIdE/P3RfSMPwaBNc5zv32KQTA/p8EoDQISqnd0LaY9ULeZ1ITAR8rGHS6M4pipAHgSdWEZcV7Ud4Y5ahTqagn8iMSsmO98o8INxU/qhZAMqkwM4=,iv:D1uflEHMC/9VM3RFcFm9sP1JgT2mk36AT7hW0bxJsek=,tag:NGrI+nOJNnUZMzwzj5yYgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
