---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: copilot-peer
resources:
  - ./deployment.yaml
  - ./httproute.yaml
  - ./cnp.yaml
  - ./secrets/copilot-peer-secret.sops.yaml
  - ./secrets/registry-auth.sops.yaml
