---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - ./pvc.yaml
  - ./secrets/memory-loop-forgejo.sops.yaml
  - ./secrets/memory-loop-beads.sops.yaml
