---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ops-data-work
  namespace: automation
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: zfs-nfs-1
  resources:
    requests:
      storage: 2Gi
