apiVersion: v1
data:
  KUMA_PUSH_URL: ENC[AES256_GCM,data:CLX+k09q/I4fUNwQb7K2eEaPbsPdSwS8Wdoq59G2lgvP33z3FOT9HTQm9U91cwzPajJLFIPZMlDOPn2IUYy7hzAxEKuFxvnUC7wdcKeiG+SjbVenYKxrAg==,iv:YjxnOkb2ee3PBVGyGDhxVuadnHISmpRDlHwGavsbWOE=,tag:WetTTZxHCnfFQbe10fvZFg==,type:str]
kind: Secret
metadata:
  name: health-zfs-kuma-push
  namespace: automation
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eVdabUhldUU0RXhZTmp3
        ZmNNWHVITmZJRnRDUit4NkFid2YxR0tWTEhBCkltdVJQSmhhaGJnRzZYdExJTzBm
        RmwzYnpYWHFuTUI1c1pXbFNHV3YzVlkKLS0tIEhZN1lVb1lERWliOU5MNFQ1WVh2
        enl0UmxwRTdaSWZCbzVXZ3B5V3prWFUKaKAN8MFfTENEHGk4+mV08uAbT69z8QJh
        gu0fLQsmzhoSlgNnXiY4Q75i5c5107fdjc6Ij+caV1yQZ3gsc3ZeAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-06T23:58:05Z"
  mac: ENC[AES256_GCM,data:gHV9s1CK6Kb0jVGqF5qySGRqKY/qQFsDIpi8lrhtApxAu9dmIiXzXoA1rKZTfbASRqqFyMg7803KuUz6av74bNcakBhdg4yeWctTyWAdxuSqjT+Xabt+5umwS7sJoUg9JzuEL80o/pD4f0dOjTpr8zn/vC//jIGLyLBYlxfGaac=,iv:xHIgvNsWkeLEE10bmx4XMaPF/9sZH95M/tEm9X9rPzo=,tag:4h6lu3x68cWitrfXJAuBjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
