apiVersion: v1
kind: Secret
metadata:
  name: litellm-health-zfs-key
  namespace: automation
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:aR5lOU9QFbaI5iVAG3pSnNJ3GpcY1ya6Pg==,iv:4z4TUhitDy7+px/Gtufl6cQLhR0sJwXO7hHE24QSo1k=,tag:fAGrP6dyfQ6q7XsIYxiYRA==,type:str]
  endpoint: ENC[AES256_GCM,data:JMh8jwM0F4qQL+SicO2Th13vsNT0Kp9nA2NAC3kfBhe9qVTodGGMdd75Yfs=,iv:RuOS3MHkG6XgNDBk3B0UXdAB98iNxj5PEfX6cTcB21s=,tag:StR8RoYWt1Q6PBrwBzzjPg==,type:str]
  model: ENC[AES256_GCM,data:hrShMzHEcw==,iv:ZF2uifAibUL3TdfT0OW8OG3PF4nVuNLIle21lUV/njA=,tag:Hm77nwRbv9mQg+BFEzV8zw==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoblFkV3EwT1RLaHBCMGFy
        M0kzanc0a0w5N01nNDJnMEVBVVNDSitOZ2tNCk5UR3VCdWw2WDR5VXQ5clRMM203
        U0ZpekR4cU5qSFVmSUdFVWV4RDVnVGsKLS0tIEwyMjMwSkk3WHNOOHk3UEowazNV
        NXUwQkFpdEpCdkZidExaOFZMYll0SncKxxH98EvfaYgoJ8GdBn9We9UtyepDm9Q2
        YIQk2zVHaJsXpn4AYmyCd0mEtUBJm8pxB5pKET4FvoEg7cjF6H4q+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-13T22:38:35Z"
  mac: ENC[AES256_GCM,data:ElWireg0i6LzAeVZfEFTnWdr0W2NlufTXhw4TupWWJoCPOt81iLJKo8+4i7GbXfxSypXYCsdgmlqNjc4ZBaA5Wj5pP6az2aKfCOPu1Y4UM4NiKnnKXjlgZXwrIio397s9FXtpKs0nlyHZt2dBJFxVlD0zICHJTtLlo3dC1u0buQ=,iv:FbdeAWszOCqKW6NbHFO+AEuFhzoYjln1ME+C/UnL+64=,tag:+zyfFJ0aUrUfP5zn+lADGA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
