apiVersion: v1
kind: Secret
metadata:
  name: zfs-monitor-ssh
  namespace: automation
type: Opaque
stringData:
  ssh-key: ENC[AES256_GCM,data:4AvMoMixkX7ct+ioNyw2Xu6hqf6xpbEX361MIeQoMWEqkeQjl38rQMnNsBhvmK7V/ANlqp7knL2ld+DvqikzmsgpVVeWBL/I6fa8XxqcBKBJFUZdf8n2u8ceHZmXDXMbxm0YzZuQI33QZamUDIaifqFNow140I0YR5iKK81vKztcGymgKMQkCjqBcHM0QPOoLv7e8BLfuXdfljJMcs8OTDEsNqUF2US6J6cEas4OO6XKmsDZYyr6/aIfS6MZLi+tr52Hm0bPVgQevNvJHC3LYPImM1lTs7wr/R5ld4WySynv024VpI/xSZUOcN8DD2hkKYHOEypzXkwBBa+ALxufxHGxC/xcNoVzReaic0aAicnWvGj4MC9NC9gZyOYEsYiQ6VmQtAku99tssCudpQCIV8uYruApibKaeS4HTjoSfOTR2Z8ec78QTEUgVvFUofIufJdMsCim6ziZmm6uxSsj2vEgktXK3rqE6jh5Ur4IjVsSkec+cjR6/+DBd4rRcVmeT/UxWOeGHXjRZTvniTDaoDo4TV69kZhXEKLNpy/76HtFHuo=,iv:iDJr8t0DUXcK46jjr8oDyvTUfCbdVzL+my/1n8wO5X4=,tag:lB8SC1OQORpzjVFGXyXiWQ==,type:str]
  known_hosts: ENC[AES256_GCM,data:PUAbiTMJ6LkhePusNRzlWG0g6SP17DASZybXNi86OynfXMoxwcZ/KISD1xaUUNA3FXOUBYDws++XTB8NbBbkkDrMH4t+pPppKrrlK2fF55lsS3k0DWnqnAdKEUV2oHoJusC+it8rF28WNwSpCZmWivVwv8waCpWKjyAC8fbRvRmJozv89SuVDIHBN3wufQ05VUvCeCA5MPkgnAaDL59r50Zf36W+qetJlMTiWt8AZWxwTRlSdIttQlmzLL18ozLob0tcxZ3kZDDHWRCqD04vC372mWQe7x0flSl4GMmiSOZz+X6LCfJxcoF2H62/zUQX1dNZLWMr1nt8qHa5S1n2xi1531Ja/difGbsm2mP78uTLJxPOy49hIJ6GFq2tHhcIt+xK4Y/hVJGMX+63e1BDqWGxEwR0WhWD98r73FCuhvlVXhnjJXWHX0EEhP3WdUmW3i+YENXK2CGIPZmZEYYhvrwtWyouxSavCxJ12Y/3LiKywJKlis3ypMA=,iv:P38xYJ/oQIHWJphQbH7W8DDOGeIyYy1GSCRKKebLHY8=,tag:ljDwFBuPq25GIZ/F6FFcoA==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIa1piYlAzOTB3eXBLR1BR
        OVBoZW43WjRYMHY3TDFXR1VscEVZelQzK3lRCjhLY1ljaHBWYm5wek5FRUI2ZjVV
        eWRjbFpzT2JwRDFWOU9kalN5QWd1cGsKLS0tIGs5WWhpTkFxTFdDNFplNXRZcGNS
        aklTaTJLU0NaMjhBdnRKUWNKVFJISHcKiNfLlLsJquNcNIscsnNzeI+8nE52uhdB
        xZ1UiOEFE7EGXMSB+ZIywxukfUp/BHX8kXTuQT5nV9P/w3lRXAyzbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-12T20:41:27Z"
  mac: ENC[AES256_GCM,data:VyARpSqgv0lGw/ZpWuRU7tcuJhYb46L2fw2QDyhVBb3xckzp+Hox1LwO8tZtipCGo7vfWmYjiuuTEYVmrnww167dkRrI6sL2+f2lpPBTwXB9tTaQU47cgGZBV5KoVGu/m2eVZ15wo2bbJyRZkeaiwwXq3mDLZFROOpNhsnnPH5M=,iv:4WJNGsBnnEnPxHEjZIarRPno7NDafZ21MfQd2YO+L6A=,tag:HVMoZ8jVSDdj+XIiwTya3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
