apiVersion: v1
kind: Secret
metadata:
  name: zfs-monitor-ssh
  namespace: automation
type: Opaque
stringData:
  ssh-key: ENC[AES256_GCM,data:4AvMoMixkX7ct+ioNyw2Xu6hqf6xpbEX361MIeQoMWEqkeQjl38rQMnNsBhvmK7V/ANlqp7knL2ld+DvqikzmsgpVVeWBL/I6fa8XxqcBKBJFUZdf8n2u8ceHZmXDXMbxm0YzZuQI33QZamUDIaifqFNow140I0YR5iKK81vKztcGymgKMQkCjqBcHM0QPOoLv7e8BLfuXdfljJMcs8OTDEsNqUF2US6J6cEas4OO6XKmsDZYyr6/aIfS6MZLi+tr52Hm0bPVgQevNvJHC3LYPImM1lTs7wr/R5ld4WySynv024VpI/xSZUOcN8DD2hkKYHOEypzXkwBBa+ALxufxHGxC/xcNoVzReaic0aAicnWvGj4MC9NC9gZyOYEsYiQ6VmQtAku99tssCudpQCIV8uYruApibKaeS4HTjoSfOTR2Z8ec78QTEUgVvFUofIufJdMsCim6ziZmm6uxSsj2vEgktXK3rqE6jh5Ur4IjVsSkec+cjR6/+DBd4rRcVmeT/UxWOeGHXjRZTvniTDaoDo4TV69kZhXEKLNpy/76HtFHuo=,iv:iDJr8t0DUXcK46jjr8oDyvTUfCbdVzL+my/1n8wO5X4=,tag:lB8SC1OQORpzjVFGXyXiWQ==,type:str]
  known_hosts: ENC[AES256_GCM,data:Amxk/LamZfx4jKdlJCAJjV54uDatCtyRSqw/nSWTLfXyX7XQ69EdSCyER7XLy0C/wf4WnJNYFirOBnxB8YQCuVTHfGEGa50to+epmmKyZ//+uLk5hbK28CZ26WYTHTGaU4CYRksFT+NC95cTnjxU1mxnUDEYrNCfrZfer4wRf6cPoroztGSlyf+MwSmWEjh9pKgUnea1WL5TG+bJSu25vH4i5R9sz20EPtAMNcJyGV+z8oXEWQ6uV+ty0nwjw54wfVuuwixUyTuhf5pVGTyU8EwRX5NQjlECshFi/bIICFZ41dN3Uat3sMm5+SuSSLvpmUZQnvlD48AQNdClHQEnQ7jTVnMrywzbBZahUA5VFDQX1omwyzLlWUnLS981hY+Td9RU83+ui1dSRF2iibLbGD4qufMMPHIhen94+RChHyweJBva1uzn3vFZshGfGUsgETwQixkHL+TGhTlKjKhkxdMHLch5/BQqMUMFgSJ1xmXJIEIY8qkuEIk=,iv:AG4heGJJHmWwob/N48HtrNbp5En4QDtXpYxpcdJM99A=,tag:gFbpITD/safDWR+OsinXog==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIa1piYlAzOTB3eXBLR1BR
        OVBoZW43WjRYMHY3TDFXR1VscEVZelQzK3lRCjhLY1ljaHBWYm5wek5FRUI2ZjVV
        eWRjbFpzT2JwRDFWOU9kalN5QWd1cGsKLS0tIGs5WWhpTkFxTFdDNFplNXRZcGNS
        aklTaTJLU0NaMjhBdnRKUWNKVFJISHcKiNfLlLsJquNcNIscsnNzeI+8nE52uhdB
        xZ1UiOEFE7EGXMSB+ZIywxukfUp/BHX8kXTuQT5nV9P/w3lRXAyzbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-30T02:30:11Z"
  mac: ENC[AES256_GCM,data:u7N/cqA8eQ/EmUpqapEDmI/y413DY1vht5YPd65r4yAwebllpNxgYjVHo3mLwg1GYiHXAWUhVm0gL07KxsndJmMGBV8BeowK/Iq3FSW19itSTwawoXII1hFK09N9ARYSQpQOI/dmtdb0xioK/VTvrW9sJQos0hTonw9umsMhkoU=,iv:QTsdzLgZVs/0A4M3o3WK2qW5OYZv6jmrnk0N7NXf8no=,tag:gXRuhjjOsK5RFSMq16ltQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
