apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:5/i3OOm8JiIz+ijwT03zIsa4CGEYIDGF2vmgLuaU9rsnwMuBHs9UW25i80xvfFrXuplgrs+wpMN8/ixBAkzQ/pkd1Ns4IYHVBH79hRcs6oPZup9ym7f94RmxBlmX1YhG+wQ4RI95uRmhjGmZ99PoXkTAMxeKK7nHG0R/069x4QZToMB3sm/GOVMBVZM/vtYv0w5XBYpGeCwZT+00J0qoBKN2dutOBmBMp0BwHnlazaFrDf5u,iv:rdn4FeW84YjexhVCbUA17e/fMinYz3aprMyJ9kAvvF4=,tag:FMt6+AXolJlAYp3/VkFrag==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqT0VTbHh2NnJmc2c2blJN
        dWhwSFZNcHFlM0xteDMyYWVhY2NDeUc4alQ4CnFXVVlXMC9jTHphT2Q5YWYyUkx0
        RGwrTEYzTVpMSmJMVUppQ0ZHY1BGcDQKLS0tIHVpYnBTb052Vk1RenBRTlBTTzhw
        anRObGtpcmJoeWRwblR5VTk3TTUyenMKswgu7JTvZ/cbs3LdhQVHb+gSqV/42brC
        zHV3BPDsE+H+crrIvV6aeVqtoreicwWes1c57RO6UDLwc5L/M4SRPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-07T23:58:21Z"
  mac: ENC[AES256_GCM,data:2kNonvrfFSL0JStlT26huN1bTvqjhhyRE5lhcxJSn5hsxFk0JirCbh6TBIrFgVLj2Fr+VC+k1ImvTa882s94w3c/uvK3Rj0LMHdJ+JGGGTqjXLs3hMedGYGnh2XxLTqz0wX8jZYUwo8DrKzA+ma79CRqgD5DP7FAA5wnzPANt9E=,iv:m8iUoFnjk1/JLSnNnxqGiTIBWMcnUJB44sUuuQ37mnE=,tag:BKjoJLRuyu70WrnSRfjdMQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
