apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:bvLtVzff/foIeGSmM4/uF9Ob8OHR5X0MznfipmH9oDrs/cVnIH7jRp7UYiRqknHN5FklJonwZeOVOtMhcYxmJECUwCiUi5vTd5p5sAqKGUwZg7JLnSjzyNHXVWXj5A10rJpa+5yDCveDLtCgJ1J0ljhu0pP06lPiMVXIMBY5Z8tIN8FnVyXlh8BRiIy51baBnijQhGk6s32AJfkKP610TFN02WlN25A7REzDGsdrk0098qvc,iv:X2uf0V9xHFlmFWedpnqWLBimnefp/cyBYROZrMkiKQk=,tag:UnP21q0ADqq1FsD5e1t/Qw==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TXQ5bit3Z1RVRmxNS2lO
        Skw1SHY2M3Y1WDg2VE5lOVBGNUFVbzR5OEc4CmxIaXZzRE05RmJra1AvWU9hbXAy
        Ung0TGh4ZWR5R0JZL0dJeEpzYmZ5Y1kKLS0tIEQzazFnM0M4akwyTFFyTFNNYVNX
        VTdSbTFZaUxud0FSVFBNSXhNQU1JcFkKAjQsS+axCk/Oyf244+tfByL7nazzQqcB
        Bf3v+s2xr9WpHQq+KBJ+TYya2/c912SH/HIzEoN10s+XLPM7tYFtyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T12:47:16Z"
  mac: ENC[AES256_GCM,data:vDVv4ePYCnd0LEP3islq7AoRTEY+yZlz1Rv3PWVdedtw7cm9bYXBnVIXgLlODp9Lixvfzo2WohOAGGfIjVIoJgWiVqA2VZo8kO5VTTF2nXqM3Okc9dRCguKx0HL0d3HdfHf0DvcaffxE1CfGYS50copaHWfHsDbc9b3RYiKvGsU=,iv:ZBaiHLz1v5S3KsPyzFOuERwyyUbXmngvVC6rc6WXi5E=,tag:pr9zh2Anb0Oi3QmgAdBczg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
