apiVersion: v1
kind: Secret
metadata:
  name: internal-registry-auth
  namespace: openshell-sandboxes
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:bMAlBA6P46ZTnykg+D+ZWI/KVLg0n8XCLwwZKgrflDXQ6lWjAvekQW7q82IswXNJ8yp4pMGDTUAF4liuZhw6RnswYyZuQlqRNSo37HGJxoswhwvpW0eRw2JoekL9kN49GlwzjPl3lkOCwOqe5VWl9Nc80AmwEWX9/krM4TwMmFilVk1unXrjRnIXL68SJAfeIj5XsBgvDmYHjYVEJuBxZw1ig47zeovnp7794sNxI+gEom3UolAN/ZSoxJ9BexgwRI5dIX61gfGEQ/FkmN4b864k94wTDJZ6KaHFWxppCgynZntD,iv:gRxS8GXbhTJ9yMjzKpDa072pNlnxckgjk5TXCfaRYgQ=,tag:qCkqk2lhFs1VJ18yt0t6/Q==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjajBvL1c4bHNCNk1GYXNy
        TmdIejFnWldkbEpZbXUvY2VKT1FWbkorbndnCldRMFlrUGc3eE9UeThuc3I2OWVO
        T01mOHRUTzVyRVdDWVF0SXpFSlV1VGcKLS0tIEdkZlFVZk1ic09mcFpsS3FXYjVM
        TzhJcWIzYURqSHpLVnB4S0lnb3E5UkkKPRf2eanSxOlaePN1+lRKv1UyfYsJKyvZ
        U7u+VGYIlTPpFgyX1uFALbYFPYAmajqpwY9ogY5zneB6vcjYrGAqNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-01T00:14:04Z"
  mac: ENC[AES256_GCM,data:LzgDmrjyTwnMYRSzTUU3AprDPlkBVmQxnBn4hnD+BelqVqh8nVh6ARmRBIaqBeluF0J0LZKaTgXkibwYzLnFk6aBjgTG32N+dU23di5jYoeHuMRkMKXeK1k5fiMODbdstugISJTV0IGF6Gy3dyDF2Rak1VWpp5yb+HZQQP0jCLo=,iv:rb9urJS1bMHdAmOOS3ZTOqxSRKVnSdBYAMryUe/pUMo=,tag:pkvm4NLKuXCMMELytYH6mw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
