apiVersion: v1
kind: Secret
metadata:
  name: exposure-check-kuma
  namespace: automation
type: Opaque
stringData:
  KUMA_PUSH_URL: ENC[AES256_GCM,data:fXVhJ/hZ6vMGHbhWXayQjiNd4eEWVDyuryYdrCS0xxTqxcCv1pTHHy0NGZSWFkyesPbVjEvlzue4JBTh+ehTeXSJ,iv:xo/KHJyPP+QyduP2UYIfm+Z/QvxDVafThdwFbcXmNd4=,tag:6XTWw0HgKnKs901tspfO5g==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSGg2K3A5ZWdGUllIVFZo
        ZjNrZWVWcWNMcjBWTVJKMlQxU3RFNng5bDNVCkJTRUxTQTBsY3IxckI2MlZhTVN3
        Y09LOTI5KzlHMnFXczl4YzN1a2R3MlUKLS0tIDhQYnhOTDkvYWpQdnU0NElHRDNr
        TDVCd2d3ajBLc1pPMVc1KzNVRUdjZ2sKScOMP95RzckeEnRapE3KjkSUQUN+xKO1
        RDX2ca90DX+K7cObFzTT63Fr/cXhjNkk1aX/N9I7ppkv+BPqQ718tA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T22:52:49Z"
  mac: ENC[AES256_GCM,data:oqphdb5Zu0FtxqW+gKnaooUpGQH9736WHOXCpM2W5kV5rUUIkXadLHJomT5LuM8WMvSWLKnX84lYUMvK3T3EwGchGqNchuFRjsIFM3GsNwS3EKCNMCzaWPm6up2PE5yk8BmQrd4HYurperzO+u0CP6jUz1NKs7P7y90aL+1/gRY=,iv:/GUsWq7kqhcdTUGh8WYsfLNSxZuCANR4ZD+RMCZS0vM=,tag:wmT+H5GmPYmHIALX6HyVlg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
