apiVersion: v1
kind: Secret
metadata:
  name: democratic-csi-zfs-nfs-2-config
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:qSKIHhat6TeyN4Mmc0MOpMcbXYY946q0lRwos3pSQAx6/hzvgcTcLlzU96evCP8awiKloWV9BJfsfkBJA4R70IT7bqOrJ5qutKwIP/Yh7TuNJ6m3oRFLx0tIWwgp8dAnje+DmIHHlC4o73KpnMOkZ09SgT6nqUY4HsshUgd8eeQti26fxapg6pyW98QOsFF7iBf6X6phRPEebFXMmAJ1MxriKPZwhU5v/UvWJy+A8FHc/zihgBvl2FvvQsgR2soxuVsW0XJW5ipoV2ixDIbnbgAKus29EL8trxyRl36efUj5Ncl9w8oGDtnLZnJb3jhAUnXp6Dg46/QCkA73uiGKECaCy2UhI3jhrUiTlo+N7KOL+VevqC+5jol0yOK1mwYduhh4CsJ6bbnI7SkyZFfSfBt4wNGO4QywbIpo1JK7g7J6MuQKz0B28O3boGmwFzvs9PHpN3zQhpoXuNsgB4CrpN8kb9wT0a0tHkDThCeFgn4pWUHKBhrhjYJ3ZXBVe9dfmMQD24zQnB97wULc4qOlQweVHi1Ta85ddT+wqqJFk9182DVl6PO+UCMKJWCxaHvPPCwS8jGyz+acp2zM6ulaSFtc01P3eGDpbemm3aQ9gPDaT4R30we1qaXqmOtSimFKJHEbN28ZDzGGVXsYV/ySaASbfzDy5IL706dmC+xq5lp+ssb4IVh1iawOPkuRYMBIZSdEc0d6OhT6ZnG/lFxFoRmNItPdoKElMe+dKbq9ZtDstUeh47PEZ61u4StFFxqGbMs/ileUxH+SL+ucLSH8a5bL3bB4Y8g/8kZiXp8NDFz9X9scemCUFFifTkc2cjlLWo3LSzgJWs2y2C/C7DXMf4jA5efThDQVOyDhrE6874em4mQbK0/RjYbjdE4ty9nI3Xa9mzvHlm+4d5a4qrQML/NoJWVwuIkABpsH0+yVd4CQ6qYuyQBH8guTTNr4o3QxjSIp8NHup934jtbp8nPnZICbFvXR3DJZAPWzacg5lKfwyYFUl7ueo9D6y5FkijnbMJvXNbAMVhWx/UX40jHXmivIl5qWz6kBb/VHuKR2vpk4PbWk8045Lv4CM9WgsCphp2o7CK9l++4M+Tb1wH1DeOETNDIPOhTBjQtS6ZX+7x/sxVjqmIS61YY0zPO7I3qAt4u1eQ1r2rXAUd92tiOQlKYf2ZrI3DkB1kOiXGNkqbe/V/SdV88uWeP4fv//207ZNVuf7/lR2tPk4/f3yBkNXQr3aT/OGs6Wqnk3BHJ+JDs9Lij6sjd0bJl/I110SwpBqhjd0RoYqxja8Mh4K5k6nkjpGw0KvcXWOCb84vnn6boh,iv:Nzf4w4ofaorrSIn2Y3tNVxThVZDxI2GJCeoaF0L7oyQ=,tag:3elXvuexOJL4nCKUoWP/JA==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2THB5Wml1L1RjbktmK3lp
        OWxXVmR6QzJPOUJuekdwZ2o2SGpuYVFrZnpvCjBZK0ZScmpZZkRWTnF0OUdDTUZC
        K2tiNjdsK09Zc0ZOcG5PbTBRVkkydzAKLS0tIE9lVmNIRVk0QlYxWnZrdm5MRW9z
        WjVkbHI4NzltMXl0YVdySGdGNUl1eG8K0oP22wDmfKeuOUndUjl/OHNseMJb+MpY
        1/HQBlWDCEveW9PFfhlmKBqPT+RPFXNSrgpf/EfZR0gYwGYVZknqiA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-02T23:25:42Z"
  mac: ENC[AES256_GCM,data:Df5JWFH6PAYtSJbZ8yO9QyaxMrAwjgYFklNyPv2mumi6Hd60zqqQRGiyOzId4gUGoSDcatqxGy3sE8k2si0Fah0VEyLvIBqIG8R30D7Vl82qN8JKGLKMvsdU5F0lJD24Eqc9l3L/X0K96vO7w4Ix0ZGF+XmUoNzKp6lqyAqZ/dw=,iv:gUaTDhW6cGV/xfeYtlFkplsICS7d4NMdVrWoCH1+kwY=,tag:uHb3FBS6hFfJYwtqlh6pCQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
