---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonMetadata:
  labels:
    app.kubernetes.io/name: health-cluster
    app.kubernetes.io/instance: automation

resources:
  - pvc.yaml
  - rbac.yaml
  - secrets/litellm-health-cluster-key.sops.yaml
