apiVersion: v1
kind: Secret
metadata:
  name: litellm-cluster-health-key
  namespace: automation
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:Tfw2g2mImddsKJDyVIfLtXb98arYOItwmg==,iv:enFFdalsQWj8xUyt2Z5sCyxjvcCksAMufTqi4L1Ipoo=,tag:RkeWsxTMY+sf7othZ2qpyA==,type:str]
  endpoint: ENC[AES256_GCM,data:SC0MKcNyS5UmsSSP0UetqywBMF1Ogh+aZhnXHHe0kE7PIdnjymJrXDs5Xik=,iv:PqGU0ko7Qqjv9EwPZ3Ttz46mtE44w0qt5TfDIJi4HBc=,tag:m1nhyBO9g9N3du2VcRaLmg==,type:str]
  model: ENC[AES256_GCM,data:agSno4dkNA==,iv:NOH7RaLXKUicWGLae4AJKVzp6fKH1Bt7ZXzgERBij0s=,tag:wHGy+WB5EyfHvjnptxr4SA==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdjNzdE1TeUVaRGRidnZa
        K1pJV05mZ0phMngxYlpNVzFGTUREejRSK2tvCjU1UXJ3OFVaZ1pLN1FUdzBlWHhp
        TlVMUGJpak9vMkR6ME1HUzhQUWVsYWcKLS0tIG83SW1ZS1hueGdSSjc4aktJQVdO
        YS8zbFZyemdPTFBmekppUHRBM0EzaTgKL8kM7vdKCzsyFICv7pYj7qI7+EM3Yyq6
        Uily6pyp46HpryL+XDqVuSfMADiVHo9u/gdVgrrYoOy7Ea6o7WLL/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-13T22:38:35Z"
  mac: ENC[AES256_GCM,data:Fp34o0T2dYeZU7sHCSSyTO/a/aCKvSBR4Kyerc3sIul/SxjOQTwd9uJ00qX75pMnbesNwfgat6IV83oPk/tEmMj3Eo79qIndBSqlf1u7QXccjHYxV5V6u9HoKe/zRU1wOeehQxymgtgZ4CYTWdOJtfHIglIuyRaAxvGRA8yd+Hw=,iv:5YUVhKOcWBw4bAxWdkyI2utIWTHSpRYzeQe4eE6EndQ=,tag:Dtlc5ZRtsglVT/kHfsy0/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
