---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonMetadata:
  labels:
    app.kubernetes.io/name: health-zfs
    app.kubernetes.io/instance: automation

resources:
  - pvc.yaml
  - secrets/zfs-monitor-ssh.sops.yaml
  - secrets/ops-data-credentials.sops.yaml
  - secrets/litellm-zfs-health-key.sops.yaml
