apiVersion: v1
kind: Secret
metadata:
  name: forgejo-registry-creds
  namespace: actions
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:uQQhLlYXkS+DIvAUMmApMLmAhon+0XfH7mM6Kaiiw8cudGY8cR3sNPIC5Jq1hbqV5GLQb07N8+wW11vJ3GzKSgPMwAIS9qpmJNBrluzQXdr/d2cZw8pyLhHD+Qja3H0vm+z4Io20FXcp3OgwBOouuKw8w764fCT9Ed7EAMcgmQuZok9pvg1UP9w4zvBcWEcYHmMcJP+wXcrZUwbwneRJPCf8ToJHiVMvmMXoNowaPZNP+2BpnqYEGiLu9t+dVmFU3Nyx9eBHTte+31v5ev4uHUoIs8lmY4/dUNc8NfDxn/89gNpl3V2wAKX/aa4=,iv:NRsZFjjLGdZ9YUcJoHp+VleuNrWCNkV7voKmTGq/h5c=,tag:l6u6V6Xzoh8YWvXkw4zHLQ==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSU05K2R0ZDhlREsvYy9j
        QjNid05lOHpwbFNPNGFXSVN0SG0zTFJGc1ZvCkQ3TUYrMnBVOFJlN2xWVnYyYW1i
        SjdGVHJQK3R0R2FZd2I4Q2hKQVMxYTQKLS0tIGE5SEVSTTJXdWtZQXFPM3lnYXk3
        cWpTYWdvYkVhaHNDY05LVEZzLzEwazAKqoS6efAtrsB/BuRrUkgXexWOA0lKDibN
        kCKJ/ZkC0S50WJKnMtOKS5Xi+YU+F97jkeTvgGtkElBT/EdR6y5Myg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-21T14:16:54Z"
  mac: ENC[AES256_GCM,data:MrKGw+SRIN0/oyvEaWzPlHli0YzsJWtcYNfQ2okPYO4aNwRjVlj15NOZgZyZf47voW1iIs28rMeHoCRebu0OKR45FRIm5eLvhArIaVEvmABni8UtHkOthi/DETRddyNEUwEdDXb9v23hODMYeUJqQJtxHMsHf0HJUxlSIXJvhrs=,iv:kNLGIrcEF4L/ZwyX8Ej/56RPoSay+woVH3NPTfcG5bw=,tag:vpwtPk+IsEl2VZe8D9y3PQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
