---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshell
components:
  - ../../components/sops
resources:
  - ./namespace.yaml
  - ./agent-sandbox/ks.yaml
  - ./gateway/ks.yaml
  - ./sandboxes/ks.yaml
  - ./secret-sync/ks.yaml
  - ./litellm-route/ks.yaml
