apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:T/JMTdtJIeGvDA6MZne1EdVLruc73cifJsuAgdmbpnOCVy/X+s7O2WdzutUE2G6NfBSHGRU=,iv:YK5y2L+RJeYpyAUtkhonXcHxlT9YCPDjhsS6PpPJp0o=,tag:S0sEHc2tNo2ZXZcm3aJdww==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQXBWL3pRSHZIRWhQV293
        TlkybW1BOGpzMVM5UTBHMG05aWlSUEhKZ2hrCkFLc3ZCdi9aMHpkZGI4Q3JFWWZ0
        c0hQNk1PV21jTStYYklqZ3F6ZGY5Q0kKLS0tIFBIWGY1dGptRWJ4azdsSEg5dWk3
        VXVNMTN0R0ZmekNjZ29ZMncrNDk1U2sKNXg6Fuqh+M10xQ2dYOLpdPBH3ux3oSw2
        PIv59CKslX5fQONZDeypJyc1fZdGxKVkn5UAaomJdhWeTPlRp9ITeA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T12:47:16Z"
  mac: ENC[AES256_GCM,data:j1Hjrd2FYw9t+07J0o6dAJrTmrAcvLEgO1atEgfwy8T9Aws48bKCsCV8RfBSjSCLVOdFsnKVJhYP3GAM/pUKNQ2L1EcMFWkzWJFSkY0Frp9Lt3evwEFxngMkgBCEkxsCU7SB5qj972BVdDwF29bVSqZwCPer9eg5K220V0WUJEI=,iv:uLQaeFof8hWuK8jUdiMolet6CrgIqPMxJcLftxctJsc=,tag:0eQU4Mp3Vk5VIzoVt2eyIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
