apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:bAUjSk39B9ZtWDjf0YUB72b2icIeza5ec/qrZtZdSxOK6eEh0NoOFcjMs1msVydLCghlocs=,iv:5pl5C2sQ1Y8yhJtADrsfrNAn1axSG9Iu6lowQtPRtfQ=,tag:/XkBcrZWxclaHV4ZhxLZkQ==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbnRtSlJHeUt6ekQ5T202
        R2NyYlBLaFNlVkJhUzA5U0U5Q1p1WUxKYzBBClNHeWhMaXhtZ3lwVWx3TDBOODM3
        MnMxazBkMXVNdjhLT0YzOXY0UWhUVmcKLS0tIEZOMC8vSGdNUkVTK01veHlXajVD
        WE5VQ0tmL3RsOHh1SnhJRmhkYXBSQUkKSTd4yD1y+GyR8I0oWFUOxtI2ag5hGL9o
        9DWcsrfLOTTV96/1MG1DXcOt4BbJYmSFJZyAEt0O190M4wcLLy0KbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-07T23:58:21Z"
  mac: ENC[AES256_GCM,data:mwTxWTu19VC01+m2k8DjMDAVDWoCOb8ba3xRNtuCGBDq5YgF80IswseAvG5JEVVhX/9yHhp0ifUPtfSVhskiSQ5/mHdIHuJj2YBTvWujMsDy9grk5LfavJLHS7IbO8/dhBSsd831njEeD128yqRcQn9Y9wknm6/f3XeCcxUzXxM=,iv:SSK3SuhviiFOzZ8OCVa7066s2RzDGqknx32hM0Fw0uU=,tag:o7HXM1RtilsrBY/pQ86uYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
