apiVersion: v1
kind: Secret
metadata:
  name: researcher-forgejo
  namespace: automation
type: Opaque
stringData:
  FORGE_URL: ENC[AES256_GCM,data:H2Z+cET5Z8xZ1r5/yqFqCB9OOsG3/kbJnVspfsf52m5IMK+oKMBz5IgV,iv:9s7qF/qrK8JR1lEN2yrxaku6/gff/NfeAIDV7X0cUO4=,tag:OAFAOGHrInclX5srsOcmiQ==,type:str]
  FORGE_TOKEN: ENC[AES256_GCM,data:ok6FIY3LE5tLNr2ps51w6maFEiOk+FMWywbrQzTdYXxyDatSLmL49A==,iv:S0djcmB3I5y0IKuLT2OTbs9SDxWIiHpGTeoB+eQwIwo=,tag:/+Ls+wIEW9inMLyM5jdmKg==,type:str]
  GIT_USER_NAME: ENC[AES256_GCM,data:Kc4IrTih1xvIPCv0,iv:eMBja5XgGa0TFiIg6BKXCS6wJS/AN7T+inHOa1Tntnk=,tag:wZaMNvOD642ftgo2w3dXAw==,type:str]
  GIT_USER_EMAIL: ENC[AES256_GCM,data:mCotJxbv4+p0jf7pPai7aqeJJ3A=,iv:fGtLq3TZt3ChWPPKGKWF+pzwEC4TXumspic8pgCnRRg=,tag:ytkNPSGCVzCO7j8/gg64JQ==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlS1lybjZuczIzOVVZUEc0
        eGZEVDRBQ0tCdHE4R1JpNWdlb2E0b1NFNEgwCmU0MytaVWNCMzRNK2pBUmNBZHNW
        R1EzM1M5QVhiMDJKRXdUZXAxd25Bb0UKLS0tIGFqV3NXeUJWRXFJSk1VZEtNYmJm
        N0FrZTllV1ArRnJlRmUrQnB0Um9oZ0UKX4U+8y14x5zZRWyiR1N5n9jNZZyf4sCZ
        TYqh+H84Ms9qdI6TTRcrShEvnUYZiMUMkjGH1T5T8U3r9vj2JMgUMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-16T12:49:27Z"
  mac: ENC[AES256_GCM,data:9VgkNl3vUEPOPN7R9jNfjpyUO+R+hYMURT3pmTlV2Jtdei6pv2PhMmM2Y3vaP+xUGTXfMrIYPVji5SIgqD6J8mugIAZqezW/ECiF+eRkmMuMTaCChDbgy61L620NpMxExXI8YbJx9Hqya+qSooaGNDwUwEcawD4FbP78zfkcK58=,iv:odNQZ81RF95upWKIBhHHcto5rAPcIM4WO4shzcK795w=,tag:C4jlpuvxyFbIolkVzbat0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
