apiVersion: v1
kind: Secret
metadata:
  name: researcher-memtech
  namespace: automation
type: Opaque
stringData:
  MEMTECH_BASE_URL: ENC[AES256_GCM,data:DsmbFNqJIKYbQoqcS7TEcqUOBjD5lAH8NdZIiJXaJEUdgKI=,iv:7HaQdJ+tcQLzTWoIzw+ZISmpvtjNwUC2iw4tcVvunBo=,tag:7Ove2G1nhYIsPifrTwv8Mg==,type:str]
  MEMTECH_API_KEY: ENC[AES256_GCM,data:Hb8KF8eB4fyIv0jxPZMMyPbHxbzNuKNR2buUuU0+Mf2efyKbLbjR6O2mOQ==,iv:KYASvdFLlaQ5uuvPnQqI/tf6YiFdV2ie9iMBN3RHEr4=,tag:vKLXorxH1ghr54Y4I208vA==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS3FkTFJZdnBENUlzRHhh
        b3VzRXIwcFJaa2FUeVRXK2pzaVdaT050dlMwCkJSbVJzMS9EMlM1cHVsQyt5Zzk5
        OHQ3dTBxY3NUSXRmY1BLNjdUeUx0WkEKLS0tIE9MY2FTYm1GU1h0bDRLMUVodnZ0
        anhOMERuR3l6aExGZ3ZncG1CNmtiVHcKTo8H3VE/7bQZxI7kmz8F1zY5+BQMkf0U
        smmnAzY0GzoyKPrJ3h9aP95m3whPp2fAF/+qyBUmcM7ujxgMyHF9HA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-16T12:41:14Z"
  mac: ENC[AES256_GCM,data:qp4C5Eeo6Z5YvtloXkCIIwyk1BxKqPuzNCbdx7J4nW/CcSO7uhsEP6D/thA0L+SGTYJLpYK/81Zwk1BrV/MExnt4VP3WtLr1Q0blzoKpT5TSpBU8ES1DdUEao0sqQj5DEDoqYG/sabGIW5e1C6IWqSZEFKX5nC33vzuHmmODrDU=,iv:URAMrFbby2n879NHxuOfFoq9GUVTQE72dyrEew8n/Hs=,tag:iGWvCufcV+TjfcjVqe5E3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
