apiVersion: v1
kind: Secret
metadata:
  name: researcher-litellm
  namespace: automation
type: Opaque
stringData:
  LITELLM_BASE_URL: ENC[AES256_GCM,data:x3C/Y2tAv/VOomjMfW/QAqmE94bVvrPU,iv:8REU1+Gwc/waqjtpaw0FGPZ0NgKjoWJdZ6FJdCm6HtE=,tag:8o2OvUk+J5atqcoeY7wgow==,type:str]
  LITELLM_API_KEY: ENC[AES256_GCM,data:p/4FEZBZOufRCizEXcMjvoA0UI+adqfgiA==,iv:X7eKclVBwo/f5NWObHoFsGYmzruz4kNnydlKtix16xQ=,tag:+KuN1Qfz9ug5ntSJ3C5ubg==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S0FCMTgwWm5pcW1WYWIx
        cVpYTVZEcmFHV3NUb1U0TUpudEU0QVFCOWxvCkx4YUlDcDh6cjY4MVgzOVByNEdZ
        YUlBKzJRZzN4c3lxdEFWL0lNWjl2NWMKLS0tIHZSZWRmWEtEUnJ2OUFEVFhKa0NX
        SFFPTFRMMmtQSGlIRG5tZlJBY2JKSGsKuKpHFD+I0oEzpuwUFDhcBr+dnoYovIwy
        9A9O4ejX5kgebVtJiPkeJo64oLkKHLNakR8+xNjdAevBXS5DkHvNkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-16T12:41:14Z"
  mac: ENC[AES256_GCM,data:lUyUSXdm+nxDRBOlM3PqIp7/rL9r2scDm7TvRj08Co8LKcb7xwOmWqyVrYzc2oRG+/RErSxwuxtrf+E06pGTooHvIhDcOcluvIrk3bipKv0r+w0O45j41CeonDZEhNj9m5uglw0ISAqu4xai9HaIkN/ZWmhZs0IUc+YKEtbbUjQ=,iv:rnqaSKu7TyF9AwzTe4DSDnemLgQL4d4n+CY6Hd/96ys=,tag:j8vLKoVAmxnJ3z3uwoO8Zg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
