---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret-signing-key.sops.yaml
  - ./secret-registry-flux.sops.yaml
  - ./imagerepository.yaml
  - ./imagepolicy.yaml
  - ./imageupdateautomation.yaml
