apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:/8u0nQT2r3tzmDBrhzGsDDU2dZqq0msIh2eJuj6lgP/8TBFL5Q9uw+zkPkxb9UL/bN5Kk8yn2SWz7VXqVeYsbsRCVjY9VZsCeZmuXAfAJMg64Serlqpe3zpBkY71OUudSH5BmTqicMnMChBkL2Jvmnx8LDfqtexyZxVdp1rBwfUsmv4SR70WIl8iuqScYuZcck1n0AXX6y8znEjmOlrY4TyVEpXdcMS6CqKRp2GWXiqPR5k+usXwoC0Gy1dhvwCd/l+0bSz17ggx2Z34AKkg/0Ff28PqhSXgyll9gbu5T30DgrNOy6ZuLmIoyiQ=,iv:nD35kpnH5kOMnVUIu8Icq98A8vuexoRY7vTz9oQDunk=,tag:P8yjU1ZjupDdCOfs3mX9Aw==,type:str]
kind: Secret
metadata:
  name: forgejo-registry-creds
  namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTFFZY2JqakQrSFRGU1hq
        RlA2dUxlbVJ3RXd6YnRVN0lrSjdSVEpKbEZvCkJmZDlTRXhoU1JhVXFsMHFiTER1
        NGhHK0FLek8yenphMUNlazlLRFdYdnMKLS0tIC9lbjJqL1oycWh3allPOUNyd0dR
        NGxRRERHa3pzS3Q5ZmZQZ2Jzc1NNbDAKRdiKfPHerMrbUGDAm+G+SAXJMjUGaMk1
        VFutzKPU7S9irgba/difwk5ienZZWpb8O76kmyk+mskvS3jg4nCPHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-27T18:43:55Z"
  mac: ENC[AES256_GCM,data:aiP+j45WxU9672vWX+x5Z6LCdfr+ns+H3xycPLiA74pKEHquO/mKrBME1Oc3Uo0Vi0xp7SufeGKhYfpbLM9r952U9sgq+y9cw+t+iVk8wDOP1FSJOJ52QRoPqjU6MqLNiTI4cdkJTpLTrhcqrgne3izCn/nbc/Iaw85Wnc2w7ts=,iv:MkWTCK4yxH7uVnd++BlgTHpQJo7JLIUTMQ5cw53LG00=,tag:pg1U5luOck6lecXaZR5S1w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
