apiVersion: v1
data:
  git.asc: ENC[AES256_GCM,data:PW4zqnwK6XYru5J1gR9CL4ElNgywnzD/XxHkWO289RPKHvQidblXr1ocuSm7ZsO9DWnIEyPDaN9NBzVhZDUYIJt0jfsp/+P6LvR81+eis06xuix/z+Zf6+/StBxjD5GuziPATnrBtSdo6FOKFR+mPNPWYs6aQN8o+tdBWkf/z66GgAgCkKEtE8bcJbPP0yWM/SGEa/sI8lnaQAknkK3VPb4HHa/IQO2iOmkgAqGM32ogwmLI0La0o25un5SabeOgogY4hTXt+lM+RhLjMeb3gOMv4ufX+wC8+8P8qWAYIcNFfdiswqPbEp7B3liXHNDQ57Zuqoiml5vxSzWieB7RhUW41PeiSK5uwrrmnk+F++YaYXebBgGJMgwx6itKFUq5+579598i+EPRtMgzllsfNKOxMKksiK822m4TjZFXghDBQ3cn5bT1+s/43Qxt4cOa4kRle4Bk14WmG84zK7fSY78O1fYrrHkbCPxD47z/HPJVIs/9MQSaje3IOWiYH4LMtB32xcZzFWqr8cEho/rYkXcGM1Szq0dcYDPSUsQWlO13MwPFsZuB8cfYYoIqwiB8rE+GqmKanYDr7S3s3nR/Kgx0k29PdZAoE0Ner2s1XaMSjWQbjTGofGE3S8FxpZ/0b57YqWLUjtXYI/p7gITuiTPuWY7lj5yT10X6CNu82RFIh4kELIM/pH6smTGanhkZhaIcMsV2nxBzyHUQUAqlkHsT6JBeqe08Ih7RdgsOEQPWwfv57pGqh7iC68Bv3xqZm+u5i6YjWYdinF/8sqsiFLzb2GjOufa/WrTJUQ0S/WVJENP/qjZg3yaNLs67Fr8/yZoPA0R7bBbNCcabMeoHK/Or40B/Qb7yeEmJxHfCj3cR+UAWCJfu3g==,iv:LTeFMMr0fjeEUs/8V2Ckl4efXjotGqEX/MM11dkyJdQ=,tag:EIuOnxPrA/5sLRW5yOzDEw==,type:str]
kind: Secret
metadata:
  name: image-automation-signing
  namespace: flux-system
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRlZTbUltYXJqejlHRU9m
        YUx5Slh1Rkt0bTlNZVNCcXlJNk5EZU4rRldjCjJ3bkRQbzFBblFjT09uUDROR2hF
        eHVJWjhFRjh4dE5KMVUwL0xwekkyTWcKLS0tIGJjdTJacnhvSHhZWDZ6cE5qYWxI
        Mzc0SUlkYk1qamJ4cTFuSGprNllNYTAKsAGSyzbV2K5hTnUTistaYxrpyjNkJqbh
        I5YjDn4NfHGtfM3+j1WeHtr7QC614rTJjZnOTeq63LR9nomZRWuJ4w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-28T11:04:10Z"
  mac: ENC[AES256_GCM,data:gr8HHqE4vOHOnS3Q6+0NhyK8ajIF95EQyJ7yztZpAaJq8YRO3knt90SRLpMhhbp/RkIXWH4zdyGfvn4P2EOrs7+jUFrAATPL66e4pJNPm2STb3NDP3XmBs4pvsOskdQlIuHLmeXRWhySgC44METvzxIUFUI3+F/qcNqJA9WfnFM=,iv:FhqXxJE7VQrN9ZW+1kWnLf58KTtGfl2CtF+8CvKh8aE=,tag:JZanOEGWD3PvPHlIIBh//w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
