---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openshell-sandboxes
spec:
  interval: 1h
  path: ./kubernetes/apps/openshell/sandboxes/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  timeout: 5m
