---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./dagu/ks.yaml
  - ./notes-rag/ks.yaml
