---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./dagu/ks.yaml
  - ./notes-rag/ks.yaml
  - ./ops-data-credentials/ks.yaml
  - ./health-zfs/ks.yaml
  - ./health-smart/ks.yaml
  - ./health-kuma/ks.yaml
  - ./health-cluster/ks.yaml
