---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - ./pvc.yaml
  - ./secrets/researcher-litellm.sops.yaml
  - ./secrets/researcher-memtech.sops.yaml
  - ./secrets/researcher-forgejo.sops.yaml
