---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-runner-set-rxr-images
  namespace: arc-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arc-runner-set-rxr-images
subjects:
  - kind: ServiceAccount
    name: arc-runner-set-rxr-images
    namespace: arc-runners
