apiVersion: v1
data:
  KUMA_PUSH_URL: ENC[AES256_GCM,data:CUOxOc7QrYHtXZPmEprRZdgoIedfpaV/349h7eh9hmHpkh4M+e3U8T0YPa1grz7CQ6TrIBEyrD5IhsSrKhzDVp/gE7yd6jvM69Rn8OFbFfh0bhP+fropcQ==,iv:LTxGMwM8YuM60u2G5Y6jUdW5h2ZXGFc74aqUQOoL0qU=,tag:g0NKYeWEhnnvo6i4k2yE5Q==,type:str]
kind: Secret
metadata:
  name: health-smart-kuma-push
  namespace: automation
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWDJ0dVR4RE5mc3BYNGxQ
        MkxqTTB0THRwaCttMHgxZkxYbmNsbTFTZFhvCjhUUjR2di9nY25MM09ZNGpOTkVo
        SlpHcmVGS0k2L01sRllPTjdFck53OFkKLS0tIDN4NGtIYzZIQ3RzQTNEMlRNSEhk
        MEdaYjgwS041YkhCNHdrTUVZU3Z5SzQK0a1dJD9AlENKhARfatRIcXyxpWIEzU9l
        yJWXlAD2GlLWQJfqGKbVPE/6vhQ/N1b+5GooX27ecbex9Cgfa6zg5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-06T23:58:05Z"
  mac: ENC[AES256_GCM,data:sTe+A4tPuObgSmDP2P4WPZBIWSRFPoJCbARqcczLW/jwOLI0PKupcrltxE1c/kH9Boah8mrC7qaSyrhRddgmQpXVXGLSkYlMX+Xb1sPBOOz9/TrWDQqGIYW9L1iMTuSvDwz+pbJ93KRP/GWiN8cc+dToEhPBvXFPxoplfBEksDk=,iv:dsduLxH3hs5NV0ys6lpoQhdTEuhc2413reXALkzcxNw=,tag:zJAZB8ANsLFnPSfO3Ph9eA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
