apiVersion: v1
kind: Secret
metadata:
  name: litellm-smart-health-key
  namespace: automation
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:aS9mnebgemo/vbXgJe2s5Z8hpQD+794nXQ==,iv:zl+rg57vSJy5Q1/aqASgRXTr8A5B40apFuTO5c79jZk=,tag:9WUERbAtK1YDKF4wJgb/Bw==,type:str]
  endpoint: ENC[AES256_GCM,data:Waj5rM5nCDUwFtUU8bxnONIDLoIyLpuhxgFwjpR9Rd5xJsExioJRoLJQnQ0=,iv:d5gs5VufMWmIpWq/Dhi014QUft81MqsI62UFiczkOIE=,tag:e5wbzvnmVNOjiqgK8X/VJw==,type:str]
  model: ENC[AES256_GCM,data:isBaKiA92w==,iv:6PIU/lXAouObgM8cCYvWWZnPm9IEm0KKuyVTuEnaKjU=,tag:yOCRMcLLdv+bNTUMElVcHg==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQnFyOStLUWZid1lBcUhk
        Ui9NV2VxMkV5cENnYklHQjNaOUR5dTBlN2hJCjNzOUQ5MGNveXA2QmpxTGo2aGgz
        aVVoUWVXTXBsckJjL2JoOGdpckxybjQKLS0tIExrMXF2VHdtb3NLcVBkUS9aVS84
        eVlnYTBTOXRUaWx5dHZhbXc3SWtwVmsKM8HvLB9QMh/JR2njSE6J9QNMv3ita+c7
        J9Y76QoDO1/UR5kWaGxu5dRTl90q9k/7dDzz300c5lwQr/o61zs00Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-13T22:38:35Z"
  mac: ENC[AES256_GCM,data:+OmENnDyBmxak+BH6w6ylUHcVFYs/dqbwnenT7E5EHLJseGmqzFnFW0THJZFHiNCv1vPBKnDQk85sgfjkbJjh13ZpgSfpXaKdshhfdzjlg1STTQkTbkWdr226e6wJxK66DgGoZS7fLuk3PEQQcA5ijhXZGHG6QLdk7BPfoSNjLw=,iv:5h4jzeUGgaetYv6Ec0WZXTFVwrQ72FTN8gCviqs/2Ak=,tag:UeCjM5I5li9hJ1lYfzPvEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
