apiVersion: v1
kind: Secret
metadata:
  name: litellm-zfs-key
  namespace: automation
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:lq39n7F9dax7P6RjlQ3/pPsGsBDNGcyBwg==,iv:dcWGE8u2M6zlD4WWqQvRKnb8g/EN8Pf/Nqyq0tegFtM=,tag:jGP92OsyJPN03bMQUfD+sg==,type:str]
  endpoint: ENC[AES256_GCM,data:8tU2CKpWEUEUqGlzOoLgnZgUXxnb+LvsjWA6HFl4nFeYX7o3luiCvrTCyq0=,iv:D8hs9LrFE8VAYPWFCk9FjyXpGV5FwzBNYKSWYWNhE9s=,tag:7TX6lx10QK+jAUMzgbTLMg==,type:str]
  model: ENC[AES256_GCM,data:exbaYxeGqQ==,iv:tnp0zNDrwb/LT2zG9uFrh3BSzFHE3XhzVdhAihqOkWA=,tag:dFyNJbUF+qgtXDGpN+5esA==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQURPQ2tDZlpxbVlqRXFp
        TnRWYk02MElqcVRkRllkL0hGdEI2SG5ZRUJZClhnbFhXRDZlNmRnckJ4SE93eUI0
        WkF2RGxKeCtDMldwY1pzekdwZHFRWjAKLS0tIGdJaG01UmYzekEzTEFFY29LdDYw
        a2FwVlV6bCttSmtNRDc5TnpBdFRsbW8KzvLbHoH1aQ5I3E5rFVLdrrZPtavv2GUi
        Zy6rI7tYaEB3ogB52Z7q4yK3D0wnG1ccigLBja3sMjN8rWhbnfNMTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-13T15:14:56Z"
  mac: ENC[AES256_GCM,data:PaoX9iNbpX7vn/mn9M+AcNyt7Ld92WDa4TsPtwix6xL+wvsbeUsYXRyfX6LIwM0oVuuWBjZA7QCjAa7ouz1exd6T1bnNIIjogro096fl6vMMyNi+RK/RYG/hs1DEJ8PqYQEzMSKBNSi5cEw9eBUaKXmRLSgHUpXhSFJnCz1J1D4=,iv:He3WxQsCqcuGbTasf3XyJz9JRRlg4JZSP6+OJgDEoEw=,tag:0N2a/CF+aBOnf1Sl49eOZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
