apiVersion: v1
kind: Secret
metadata:
  name: ops-data-credentials
  namespace: automation
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:GuExti0Zd9Y=,iv:l47FxlNpu3TCWTisrulghmyhBGGo+o7LKDakhTi54MI=,tag:PH3MMe3eBwDDESTUEm6hpg==,type:str]
  token: ENC[AES256_GCM,data:ivMmeWL6NR+yafjwnOLEFLiqpeWmqF37DLJSgZ9mPcWTZdbiOvkgqA==,iv:7kchd0mrd7geLuUWMwyqLOesCb1wuXNlBtovxu5xkug=,tag:pe4jBkjHL9Y9RibAlGKIew==,type:str]
  repo-url: ENC[AES256_GCM,data:V8dlHfZZfs77paLJty+T7XUWUTiMiT/++fdUXBK9V1Je1Jip718=,iv:V9bnZCEYUXytNNwKVNdZYBB06Fk08JcJqW/oWvF4jZM=,tag:xRr3Q4RASwSvZZq6SSGHkA==,type:str]
  user-email: ENC[AES256_GCM,data:HvM5DhfJlzsEd/0FRe5fjvGlffnL,iv:IM/uv6xlK9muTkeWAnh7p0a1Ci55e8YICAgCckJ1Tvc=,tag:DvF+gGCtTM0jSZZkO13i/w==,type:str]
  user-name: ENC[AES256_GCM,data:VoMXli0PTBbqJDWXTteEUJQ=,iv:P9QhwXcyZEVOK9DBXYL9Z/cMrlhX2QH9HbpEhUFcBB8=,tag:2lghaU6Q7d3JSSdEI8hUbQ==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSVU3TG0rRnNubmpmVHAy
        cUVPL1JoSWdIcy9oQ0swRjRsK2k1YTFJRldvCmd3TzFxTmdsaVdLNTd2Qm1sRkp4
        aWpnZjErd0hwaUJUaURzUzFZcmZZKzQKLS0tIC92M1pMOWpqQzQ0SkI1MGtSSWRH
        QmI1MzEvbXhYbE1RTi92cnZ2bWFxSDQK79Hc1LZu6ea3xWseUmIdtAJTxfr5Ho24
        w0Bp7EDuc84ursIys0BlioyAyYbj7fuiLLNtCS+3BG2gVNrQryfemQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-13T00:34:40Z"
  mac: ENC[AES256_GCM,data:jhfzKyEcj9riL0s56lVgp3k878t5apx+7u3RuCcdpTMh7wiALE1U6W2SI2q46y4HqhUQFenTE4mWBEgmk+zI6Gz9taTwuyhDcNVHvHixgg0xZTktxNMvkUPCJcdVmg5Yf7W5z1+7+ml0gi0AZpFTeHdNQZg3cyVNkhYprI57jtw=,iv:8c+JrzXR2Yb9rHSXw3xOXa/gt0/Tg8m+1VL3epngVL8=,tag:Tri4tl2Ho5sB26UP692ahw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
