apiVersion: v1
kind: Secret
metadata:
  name: zfs-monitor-ssh
  namespace: automation
type: Opaque
stringData:
  ssh-key: ENC[AES256_GCM,data:PuHYwH76mbqvXLHFXUYLxXp1JnsvVCGx0aZ/bRusoZ8MMqoOv8amZ/pqupX+aazoYhkPZznTCvuRjXNZ9/AoF060pQZC+vJus4Bkr82Ve45xFty9R4DC0A3TUQZkpOaEYMCESRQeSQRD08CGPmML8Z/r7i6FD2ZrIOhtvSAVyoDCTWf1rQZ97jm8JIZhKn86jWGC5fie23NInKeucA7q26/pB5sgGLCCUxWiQjELGVi/S3Nb4USB0Uvs0h83xa8BqT0Fy9Mh4yisUQDvCywIZsRA+4oAT+cl7AF3VNwJUcO7A5ptGgM6ZwMh0XZHDilBMbHZg1LmkJVARjf2W1B6Yb4CuRucZSWi2F9g9AQXf0vyC1WaI5NEC4y4aN64pymfcFTX7tgHBbhydZDiIE07+qlWK50nRIARd3sq3WyA5yTtSzyND3SqjMZxbxQwGWBnlbR53snq2qnVfb1YbPk7O4rokFbpKJ9raVsec4lkcC6Aheaz8USswjikHOuEwg3bpUgYE7D4w1mvF6Aavn81926ldZs9mFLDVrwjhelnrwtstQ==,iv:1nwpL4qePgA7qrKw3UTkK6mUKqKUADOO9oOutSXOCEA=,tag:pmuJ21z9QogXaG8MccS/qw==,type:str]
  known_hosts: ENC[AES256_GCM,data:PUAbiTMJ6LkhePusNRzlWG0g6SP17DASZybXNi86OynfXMoxwcZ/KISD1xaUUNA3FXOUBYDws++XTB8NbBbkkDrMH4t+pPppKrrlK2fF55lsS3k0DWnqnAdKEUV2oHoJusC+it8rF28WNwSpCZmWivVwv8waCpWKjyAC8fbRvRmJozv89SuVDIHBN3wufQ05VUvCeCA5MPkgnAaDL59r50Zf36W+qetJlMTiWt8AZWxwTRlSdIttQlmzLL18ozLob0tcxZ3kZDDHWRCqD04vC372mWQe7x0flSl4GMmiSOZz+X6LCfJxcoF2H62/zUQX1dNZLWMr1nt8qHa5S1n2xi1531Ja/difGbsm2mP78uTLJxPOy49hIJ6GFq2tHhcIt+xK4Y/hVJGMX+63e1BDqWGxEwR0WhWD98r73FCuhvlVXhnjJXWHX0EEhP3WdUmW3i+YENXK2CGIPZmZEYYhvrwtWyouxSavCxJ12Y/3LiKywJKlis3ypMA=,iv:P38xYJ/oQIHWJphQbH7W8DDOGeIyYy1GSCRKKebLHY8=,tag:ljDwFBuPq25GIZ/F6FFcoA==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIa1piYlAzOTB3eXBLR1BR
        OVBoZW43WjRYMHY3TDFXR1VscEVZelQzK3lRCjhLY1ljaHBWYm5wek5FRUI2ZjVV
        eWRjbFpzT2JwRDFWOU9kalN5QWd1cGsKLS0tIGs5WWhpTkFxTFdDNFplNXRZcGNS
        aklTaTJLU0NaMjhBdnRKUWNKVFJISHcKiNfLlLsJquNcNIscsnNzeI+8nE52uhdB
        xZ1UiOEFE7EGXMSB+ZIywxukfUp/BHX8kXTuQT5nV9P/w3lRXAyzbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-12T19:47:00Z"
  mac: ENC[AES256_GCM,data:otYyQEfwG6alHyy3xvl+lRgJwitFbZD59MeklyAL8njfQQmHdXp7ZewC+LIFHHz1V0iefS6unfjjgdGgka3fFwgQzmbnS9mveU2yP4GC+3c9OeqPxq4zTfwbaNUtj/GK3Tv6zNb8j/AqoD6ZmVFQ9NXfYrPBLB4u6LYi7D9foHs=,iv:Sj7uWY9XNkPOj8Qhz8TVgOakGP7hYQgMjt3F1FVfmk0=,tag:v1SevWFmEhWi3m3Pr+GNug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
