apiVersion: v1
kind: Secret
metadata:
  name: zfs-monitor-ssh
  namespace: automation
type: Opaque
stringData:
  ssh-key: ENC[AES256_GCM,data:SINb1fcaNVkysWK+gH/1pzBehqOsbgxL33v6syOy3HnPr1xYxlgXmwkfMiNbIEhiMGXdHzz+kTA4xvUfs44MgLZMXMyjprbSiuRMtVN8nb3VYajBkjL2DgpUBsg8ZIdicERLz44q51CW26MyPB6YjxFy86CM+1WU7U3H0dX+iQRbZnf14EUY4iQ+fU7Af/BLgd+QinTqvC4b7LwGwE04GhqNTCYhJOUiODtn6LxiAHCdE6FYdECnCMMnHL8Ze4RGxki7uGVjsPmPYXB5Ljywf0FHlIGv8My9UP3+CkRqhj4YufFISRI1x7HBWFFRDpbn49GKzlily7Z24DUaMRtIe2YOFDv0M78QtJ2Zi41Jg75OaoePgCvZDQ3DArLVbaMuUNmFeLC+Bnx8QL8bW//caLqvRbHokaHCreAP24L/o3G/4nU/H7IG/mW/Y7Ve71Z5MtGeeqI1aLC6CkUZ2fttWZGVZTVbbnX4jzW4hXGVLF9n5Ssicpk46KXxQWOwnYSBW5twpX9Eq8n71vm6U3QgKsT5bLLUau2R8K4J7HMYHBMhRsU=,iv:j7A1+rZd/j0I46S3coumWhMr/8cnqh5TnWUPWjZnoAA=,tag:DMTtO0AZ77sR/A+zOnqWUA==,type:str]
  known_hosts: ENC[AES256_GCM,data:PUAbiTMJ6LkhePusNRzlWG0g6SP17DASZybXNi86OynfXMoxwcZ/KISD1xaUUNA3FXOUBYDws++XTB8NbBbkkDrMH4t+pPppKrrlK2fF55lsS3k0DWnqnAdKEUV2oHoJusC+it8rF28WNwSpCZmWivVwv8waCpWKjyAC8fbRvRmJozv89SuVDIHBN3wufQ05VUvCeCA5MPkgnAaDL59r50Zf36W+qetJlMTiWt8AZWxwTRlSdIttQlmzLL18ozLob0tcxZ3kZDDHWRCqD04vC372mWQe7x0flSl4GMmiSOZz+X6LCfJxcoF2H62/zUQX1dNZLWMr1nt8qHa5S1n2xi1531Ja/difGbsm2mP78uTLJxPOy49hIJ6GFq2tHhcIt+xK4Y/hVJGMX+63e1BDqWGxEwR0WhWD98r73FCuhvlVXhnjJXWHX0EEhP3WdUmW3i+YENXK2CGIPZmZEYYhvrwtWyouxSavCxJ12Y/3LiKywJKlis3ypMA=,iv:P38xYJ/oQIHWJphQbH7W8DDOGeIyYy1GSCRKKebLHY8=,tag:ljDwFBuPq25GIZ/F6FFcoA==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIa1piYlAzOTB3eXBLR1BR
        OVBoZW43WjRYMHY3TDFXR1VscEVZelQzK3lRCjhLY1ljaHBWYm5wek5FRUI2ZjVV
        eWRjbFpzT2JwRDFWOU9kalN5QWd1cGsKLS0tIGs5WWhpTkFxTFdDNFplNXRZcGNS
        aklTaTJLU0NaMjhBdnRKUWNKVFJISHcKiNfLlLsJquNcNIscsnNzeI+8nE52uhdB
        xZ1UiOEFE7EGXMSB+ZIywxukfUp/BHX8kXTuQT5nV9P/w3lRXAyzbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-12T17:07:20Z"
  mac: ENC[AES256_GCM,data:Pnb+MVwxBitdcVHjpw7pyKKdANNkjbdIv8/vq8llJiZ4KyY7L1C1Yanjk3ydNPKa90BtEwyZ9qYkiBGKmm4XXcfhf+Z3B9DBM/ZVOuvj5xwZ//BuZcG6mjt7mNr+hXNaSnpRriV0LLvYUCHCApgJqiwkoRkZtZYsXHsA89L+/Vs=,iv:odo6K33TXcg3sAxVTDQmfyFJVDPm2rBReeiy4rHGsPw=,tag:oLY3oE7EvZeSvx5oVSyorA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
