apiVersion: v1
kind: Secret
metadata:
  name: zfs-monitor-ssh
  namespace: automation
type: Opaque
stringData:
  ssh-key: ENC[AES256_GCM,data:SINb1fcaNVkysWK+gH/1pzBehqOsbgxL33v6syOy3HnPr1xYxlgXmwkfMiNbIEhiMGXdHzz+kTA4xvUfs44MgLZMXMyjprbSiuRMtVN8nb3VYajBkjL2DgpUBsg8ZIdicERLz44q51CW26MyPB6YjxFy86CM+1WU7U3H0dX+iQRbZnf14EUY4iQ+fU7Af/BLgd+QinTqvC4b7LwGwE04GhqNTCYhJOUiODtn6LxiAHCdE6FYdECnCMMnHL8Ze4RGxki7uGVjsPmPYXB5Ljywf0FHlIGv8My9UP3+CkRqhj4YufFISRI1x7HBWFFRDpbn49GKzlily7Z24DUaMRtIe2YOFDv0M78QtJ2Zi41Jg75OaoePgCvZDQ3DArLVbaMuUNmFeLC+Bnx8QL8bW//caLqvRbHokaHCreAP24L/o3G/4nU/H7IG/mW/Y7Ve71Z5MtGeeqI1aLC6CkUZ2fttWZGVZTVbbnX4jzW4hXGVLF9n5Ssicpk46KXxQWOwnYSBW5twpX9Eq8n71vm6U3QgKsT5bLLUau2R8K4J7HMYHBMhRsU=,iv:j7A1+rZd/j0I46S3coumWhMr/8cnqh5TnWUPWjZnoAA=,tag:DMTtO0AZ77sR/A+zOnqWUA==,type:str]
  known_hosts: ENC[AES256_GCM,data:qqFFNogY6vVanOx35JRokxpHwFdb78Z2n2Ag2Nd9bzP+aUFoCxlGyF6htlKni5fcqTvuNHVGy5RYJzxiM7baIqIZgPQfWWhzxnYQmXvYbj8DiV4cuLGyWx7AMft8uZKv96jpmpCUBQM2VAV9ko5uCUGs9WLP9ODbslae1Iso0raPdt9ILK5bnNQHTxOhs66aqKm5yKklLNy1Zggnc8WiZzD4Dd4dHARHZm47T3InDyfg1nSyUWnBCR6Kwr6EdUr4glH7J+MqciCBgLCoTIYK6Kdzd5GjL03fCCLjCzIr+q8YmfYh2nyaCZY0P7olXjTCZC5uZomdctvjLxAZ87dsPI9n0bi8LlAA9avMs+oRRztzpjufKJVszNbeiYR7OhTrOQY0P9Nu8q6yMu6yVAQotAnD73sHlGNkK+5fuHBp1y4kLrkHkBolpW0FrWlJfxyrpRKhcu7+Kai61yn3c2qrsZoR3KpSUuDGwXrYenCgVh5yPUWC6VH8lqQ=,iv:rPuJBbTL8iur7HflpxVvLl/+ysHcW2KiTz9Gjnmy/ho=,tag:02kKo0kFzxGh03Nv5j+Fhw==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIa1piYlAzOTB3eXBLR1BR
        OVBoZW43WjRYMHY3TDFXR1VscEVZelQzK3lRCjhLY1ljaHBWYm5wek5FRUI2ZjVV
        eWRjbFpzT2JwRDFWOU9kalN5QWd1cGsKLS0tIGs5WWhpTkFxTFdDNFplNXRZcGNS
        aklTaTJLU0NaMjhBdnRKUWNKVFJISHcKiNfLlLsJquNcNIscsnNzeI+8nE52uhdB
        xZ1UiOEFE7EGXMSB+ZIywxukfUp/BHX8kXTuQT5nV9P/w3lRXAyzbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-12T16:45:06Z"
  mac: ENC[AES256_GCM,data:NMGCy04m2VJZe/4ePBmn2IZmlaESfxPfpqTWoWDiwZnqfLAICzPG2RSo3dmNBaxkd+OiLG/XN0Usgk/lDzZ+Yz3vjgbRJxXpMlWsEPBHxEjZNoPPZXCYyNhe2S+HMXlDQq/n/LqEeUV8CfcOAK18NqydZPN6g+KvJF7bS6cJBwg=,iv:gcDcidTEl7Gia7q7opPwEBFe6I6oWebVDKYKeNMUyQQ=,tag:z8CbKaRXeXiz+lBR/NN6hA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
