---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonMetadata:
  labels:
    app.kubernetes.io/name: ops-data-credentials
    app.kubernetes.io/instance: automation

resources:
  - secrets/ops-data-credentials.sops.yaml
