---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonMetadata:
  labels:
    app.kubernetes.io/name: smart-health
    app.kubernetes.io/instance: automation

resources:
  - pvc.yaml
  - secrets/litellm-smart-health-key.sops.yaml
