apiVersion: v1
data:
  KUMA_PUSH_URL: ENC[AES256_GCM,data:XeiroMtL/EgtQiL0pjpXkQNk89Vzd2D/HRVxuRPsW9hZb3IMnOLagi/7+kFej9u7o+v2Ypl+s8enrKSTL3SIn0GyWFuyIivvgR2ZHS43fE44NhRLo27uaQ==,iv:NfnnrK0NA/iBSa8ZqUMNIiXHE6Du87mtR+MVH87WFmU=,tag:QP5lK9Y7ihIcpNUuJRsy2w==,type:str]
kind: Secret
metadata:
  name: health-cluster-kuma-push
  namespace: automation
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbjFMMGsxMXJ1aTZLNXhm
        Rm8xK2xrZFM4RGFrV0I4bENnNko5VnFmc0FNCnUyU3JYOHpNaFcybXpLd0ozOVhZ
        VHBxdWgrVGpyaGN6MGVUbGJkL1hmZGsKLS0tIHgybXBwdUJjTGRGRkQzQm5PK1JJ
        T21VUEl4WnpPM1FuS0wrbk1mUEpUOEkKkQ3bnCmgq1w8JTnQMGMls3TLIYBsjw1s
        6OFVFe+zUOcVVYKWwzeDPV+A21sw2myw2cJV+iywrdJk/F1T0tntRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-06T23:57:58Z"
  mac: ENC[AES256_GCM,data:LnbctNZ517XJD1gmYvJR6l3dBPpu81yNzQ70FMC59ojjmYFSiM1Qn1277riPdTOAUHWgxgux4DoKk8kDlFaEE0HVwsd+tgh57vf9msfMVpCWweed8rpbWATdvhjud7BztYPRZMjhisLHiaqcn1C6A/FxAAAWoutQHZhS6OdP6V4=,iv:vW/3NBlAecMj283YN27M4ZMCculi/YasMVK8STdt2Mw=,tag:T8NM1OxftD8SCApJA83t7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
