apiVersion: v1
kind: Secret
metadata:
  name: notes-verifier-forgejo-notes
  namespace: automation
type: Opaque
stringData:
  FORGEJO_NOTES_TOKEN: ENC[AES256_GCM,data:vRUytSLVZd8rWVJ+Q3DMUhCGhn5J+bbJxKVEudI2FcAuv/6B250S+WTcMnuBpXCsVI2wr1Dlqs/YazA=,iv:w085IkbBUVXcIyAPWzLcOptPpLDfMnl5XylurzNNQ+E=,tag:JZmV0v7DzsxIYtLQ6nCEtw==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTWtFcisyaWVVUng2d1dP
        TzIvQUhyempFM3RPTmVONExqRjRiT3ljaEU4CjVGeDMxQUpCTVY2Sk04OFpHeUk0
        REtBajlScE5aNTFaaEo0V1ZObmhNS3MKLS0tIEM0UlBEWSt6aU1XS3U2aVFMb3NQ
        bkNMNWQ4YU8wY2pCUWVmWXg0dXd1ekEKga36HmTdgJZp0Y7Lc5eB4SuX/Jp86Pcw
        r45d2Dz2PPcdP6J0qMVmviOkhUCupXDCtDLl2zmtk/RMtQjjPMQyuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-18T00:49:05Z"
  mac: ENC[AES256_GCM,data:haTfX+LrE/5uI23Mh6nzGeB4wrC+fsT84czx2o+EaueZTSSDGsJR1gMBZaP7HQ+/oSuChe1xLDRYOLUt8sigbH3OdH87bFS5XVCB4Ks2vbGD5wuq29TaFBul+iKWq2zvZMiRmgBpEuaDJal+O4LQ/bk2F+8L1/u/ufUUGfiOrDM=,iv:Pw1ulpdH5zjABGrczARUyr3ukELqeOt/1JYdkOBLp1s=,tag:sZD/BEBCkUlvisXlmm36YQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
