apiVersion: v1
kind: Secret
metadata:
  name: notes-verifier-forgejo-drift
  namespace: automation
type: Opaque
stringData:
  FORGEJO_DRIFT_TOKEN: ENC[AES256_GCM,data:XFKQcHxJSFlofzrLnScDGfJ8y72zHX06S9MeU0Ku1zRLscREDbpBmA==,iv:wsnR1307fI4l0ozbRbIfURSkvlSqM8MK/G2IIPm26PE=,tag:a8I3A700H0uw5RhAi0Z1xQ==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdnRlaWdUYStOeXBNVDVS
        ZUJuT2ZNTzROTHZJNWhPRTdLWkkwdkVLSWpNCndJVTA4STl2S1Q3S0VQcTcyVFRw
        YUN0VERZbjBxaituRFV6cDByNTZSaHMKLS0tIFk2Y1ZIRVgzZEtwSVRhN3NHeW9H
        Qncza1NwRDI4K0xlWDJsbmh1TGZpeW8KwqhU6fLIzrAZf9UUtS06aLGMx61/diCv
        hLjw4plnCTH93AAcaVjcqgz9z3dpAzGMXtm9SkCgdQcLX/lrTxdCVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-18T12:36:43Z"
  mac: ENC[AES256_GCM,data:YGdDYA11NPtkTcV/c/FICm0WmZ4Y1po71vBZcqDrlZ0mJaf1IqrBlr8EAW3nlJ8A9Ta8Qt6zpxKv3D2FSFypiwIptLjeHiMBKFiNizddFnIPKuRjpbCKrn7JFq16arZouEPLkEZps8FaO335yY0C8BqQTVTIhmT21SDhL9owR1g=,iv:8LD2/3HONfYw2unDwBzxdK+/WxyjQ3QXkqgp/iFLJMo=,tag:Qpxhigd8nd4uM6cuQHfj/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
