apiVersion: v1
kind: Secret
metadata:
  name: notes-verifier-litellm
  namespace: automation
type: Opaque
stringData:
  LITELLM_VKEY: ENC[AES256_GCM,data:L74Ag+AJGbII1nH6352K7oo3oGrWbasPuQ==,iv:EmadJRURlWtsFUXV/BztoC8MV9kpb0mAOp4xVZGFTdw=,tag:D6ZKF03bILrecqwTBbKrDg==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLT3pSWVFUdVhISHhYZ0gz
        WTc1ZEdZdEE3eU9ZZWZlWlNUUThGMVgzWHkwCjIyOXpkZTFoZnU0SWErbGprbUVk
        YWpuMjNwbXBUeUcreWF1NWlJbkZBYkUKLS0tIEFPcDcyN2JwV29keXNiMUZybmFI
        clNtNWlhdTJMRFNGcTg1bkV5QUZ1SEEKcrGiXH8b+gGbWrwKByrSgmJnRELKUUkN
        zLgD7f8Kb6K3r/qPVIa6Ap5wSv/YxF9XLzV/OBFiqZI3OFF/sfwaUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-18T12:44:22Z"
  mac: ENC[AES256_GCM,data:XQSDKnxAN6iP+BI+qZ1yV/FhrwkTN3quYhEa2ESZUFZErYEQidKawf5OBcODxONgAyp00BHFaLWdd/pSBmnhpwiqakhjMgGAhTwc7DWR/hAeMna0bbw9Norj8f/KVolUutDAJLrSTAP4DW1Yc/Zr+y545FD8+AQTrB9f2Xsd4C0=,iv:9/Erbs6AF/GfUmvjgauj20Dqx9xtdlD2rmtmKuqBP0w=,tag:c4OA/Nmefojd9o+jXxjinw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
