apiVersion: v1
kind: Secret
metadata:
  name: democratic-csi-zfs-nvmeof-1-config
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:MlM3aeMYcBaeMvJEOGc0OGpGhXBOkN0729mGNAhXFVc5RR9AOON5gMDgRV/TxJHVMYpxztlGSr8bzJvlg7b6lWUaJXysAz1gVTfZyXS5pwPUpbgBUeaAS6FT2i1nTOLlsd/VKeBPpr9+tikLL9hQv+tkN2IRdAhH5n0rZoa5yUDeKO9ly/szmtz1+GjZRAjeZYVOoQpPBHl3PrT17wfIpV13hoEc+nTwj0ELG8cnlei1xIv7ZGXWbZQSGseLq7yHobNXQdt53Jhtm8HSXQPtQExI82CmcHMb7IC1U0fOO2xTpZyKGhvzMvJR/3XY3i6PXzb4oQ8wgLPt8BXTTinci0zB74Sa1H9VmGTMfYSqoirYdHnhSBO+txlQG5BqbEl8ZKMgdN9MxeIZqThQC2p8WGizUsHVrTv+OQ5IWQilmUL87mtCYpayV+OFp0wGZVqN+Q4vxU6ygqPRdnxmgHd/2aBhAEStvMT9t31UKWKXnMpWaqJVuELTZm3MdfWTQVorv+fwkm2VCxUcV8FLgoySVasnU1UezlBKkO3GcOL0Zn929n8+M1L5iu+Eh4FtNDjCTHjUKEep44x1iUeu866vIVBj191AA+OX8/eh6SMJW9GgS5FcxVSDhrng4DtP0wS0S3nYAuIwmNPVSEBUwbr/sqrt77LuJbRwhmLPq+fO1IE3yZl9az6F+LtlI/bQU/0MI9tA52ukPZNv5daAZqvmNF56u3ouCQQiJBPGP0uoq67jWC8cVGLf6gqMEKHWpfJb3j+CM0XyEef1kaGiMGoG5H9pA30lK7/CsUqEzbomfPd9W0WGC56TaRMe1jLWU356chEx2F3eG6xrPPNFt0GCgo+1ejmQ79vxPSZVVwog20NnLxMa5Dnr9kW6Jv0RoGp/1CHkgpCzLvPI69L3qnIjcAaIK7G1jh7z3vQoMv0xxEnMzT8fkaL3Wi1vqfnJNgg+AzJNW9W14tRpgZ+terAuS5UDQvCAqv/sX8vRK+YdHF9sTsmON9KnKC6WR7MECUgV1nIRYRbKimkmP/IvVlOhnSasCxIqcaIXiVOa1QW/akYcQIJCD5ihJR1WbSS4QK8SFnk0WN3pQlSQa+FZwNAkQJZiMnCJMr7qH28YPEz5EClmNUiwKlBRMhIWfgJNDD71nmp8Avir8d45Tv4GD+iHNk8Vs1XRtaeTIIKRiXIgkDHFTT2voEzF+585Lmp4KMH2kosb35/GKEE8BJ1sPsKs4kNbiH9sZa4ozIzbCbJpDOc3X6WbcakS8j/Dedhmnb1j8k0vROGoKCRnammbzxGzMAtw/1ujDPIL/5zEkY1ckJjihjONtFopQ3B/r2nllhwciCpTsbqATifTZPjDh6aoKV965BnXQbQCFzhjj/f8JA==,iv:mIydM+QQwlgQ68T3+iQByydsXuU7HZeQEul1TN/JdII=,tag:yb2oM0VIcv2fzW7nw7JHlA==,type:str]
sops:
  age:
    - recipient: age12rzq0cuqfyh8syej8v26530zhhcag0d9pdsms5sp3c7d4llu7dwq9y2lw5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bUhCVVJpNjhJd2dqNFpa
        aVBrek52ei8wMHBrWlFtUWVqRFVLQVhqMkhnCjJNRGVKYzBScTFlSHVBQjdpL1Uz
        dDRNSitGZTBGMFdidjQ2Z0tpeHY1Z28KLS0tIHd1Sm1jV0FBWnlZVEtkMDJzWkNz
        RXZGSDVSdFVicW9GOG9KZmF2RG1kM2sKuIWCh0UBqkvIRmF81tWJasOPiBGlHwCw
        NMC9RBb5aes++D6RUyEEd3/y3VmO1MLg1KehX/AfBg3SBPMABp+Udg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T14:40:49Z"
  mac: ENC[AES256_GCM,data:DF7ioyl1v+fxTlmCBd8eTE7BFhOlwAtHe/ritXVlar1dX/MZ7CH8IhzskxqiVwHjB4RheN2T9Jexfslz79xuunSVTeR4viVOiM+lHxQNb6wkRjMNN1zWdAbYbSnckJ6BWlJghah4ajPsgWRPrIp40G+4x+dBeXntelR+jS1ddbU=,iv:JZKibdl0dQX4Hj0fJtpK/pxH+LT+PzZ6IsU6rLp5kig=,tag:TtPv4dhRLajZNGeTK4KVaA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
